infrastructure/environments/dtos_dev.tfvars.config
infrastructure/eventgrid.tf
infrastructure/modules/event-grid/main.tf
infrastructure/modules/event-grid/variables.tf
infrastructure/modules/shared-config/output.tf
infrastructure/variables.tf

feat: implemented EventGrid topic

---

infrastructure/appinsights.tf
infrastructure/appserviceplan.tf
infrastructure/environments/dtos_dev.tfvars.config
infrastructure/eventgrid.tf
infrastructure/fnapp.tf
infrastructure/keyvault.tf
infrastructure/law.tf
infrastructure/modules/app-insights/main.tf
infrastructure/modules/app-insights/output.tf
infrastructure/modules/app-insights/variables.tf
infrastructure/modules/azure-sql-server/main.tf
infrastructure/modules/azure-sql-server/variables.tf
infrastructure/modules/function-app/main.tf
infrastructure/modules/function-app/variables.tf
infrastructure/modules/log-analytics-workspace/main.tf
infrastructure/modules/log-analytics-workspace/output.tf
infrastructure/modules/log-analytics-workspace/variables.tf
infrastructure/modules/shared-config/output.tf
infrastructure/sqlserver.tf
infrastructure/storage.tf
infrastructure/variables.tf

This pull request introduces strategic (short-term) logging infrastructure enhancements to our Cloud environment by integrating Log Analytics Workspace and Application Insights with Azure Function Apps.
These integrations offer immediate monitoring and analytics capabilities, empowering Engineering and Testing teams to gain valuable insights into the behaviour and performance of deployed applications.
Additionally, some code refactor is introduced for good housekeeping of Terraform modules and configuration variable mappings.
- **Enhanced visibility**: With Log Analytics Workspace and Application Insights, we now have centralised logging and monitoring, offering comprehensive visibility into system's health and performance.
- **Faster issue resolution**: The analytics provided by these …

feat: added log analytics workspace and application insights for initial log integration with function apps

---

README.md
docs/user-guides/Setup_GPG_Key.md
docs/user-guides/Sign_Git_commits.md
scripts/config/markdownlint.yaml
scripts/config/vale/styles/Vocab/words/accept.txt

Update current document to include some missed points and to include the steps to download GPG command line tool for both Windows and Mac OS.
Updated the pre-existing document to include some missed points and re-worded some points to improve the readability.
Added instructions for creating a new GPG keypair for both Mac and Windows operating systems.
Issue Number: 2532
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. …

docs: updated user guides for using verified commits

---

.devcontainer/devcontainer.json
.vscode/extensions.json
scripts/config/post-container-cfg.sh

This PR includes adding a dotnet feature for the Dev Container solution (with C# Dev Kit VS Code extension).
Dotnet is required to be able to natively run build/test commands inside the Dev Container.
---

feat: dotnet feature integration for devcontainer

---

.github/workflows/stage-2-test.yaml
scripts/tests/unit.sh

This PR enables unit testing for currently available tests when running a CI pipeline.
After testes are done, the testing status is put in the workflow summary.
This automation helps with continuous code quality improvement.
---

feat: DTOSS-2785 - Unit test integration in CI workflow

---

.editorconfig

fix: sln linting issues

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs
application/CohortManager/src/Functions/ScreeningValidationService/FileValidation/FileValidation.cs

… and builds ValidationException in filValidation function
now only sends rule id and file name to filevalidaton function and builds validation object in fileValidationFunction 
---

feat: now only sends rule id and file name to file validation function

---

application/CohortManager/src/Functions/Shared/Model/Enums/Status.cs

fix: short type added to Status
- [x ] Bug fix (non-breaking change which fixes an issue)
---
- [x ] I confirm that neither PII/PID nor sensitive data are included in this PR and the …

fix: short type added to Status

---

application/CohortManager/compose.yaml
application/CohortManager/src/Functions/CohortDistribution/AggregateDataServices/RemoveFromAggregate/Dockerfile
application/CohortManager/src/Functions/CohortDistribution/AggregateDataServices/RemoveFromAggregate/Program.cs
application/CohortManager/src/Functions/CohortDistribution/AggregateDataServices/RemoveFromAggregate/Properties/launchSettings.json
application/CohortManager/src/Functions/CohortDistribution/AggregateDataServices/RemoveFromAggregate/RemoveFromAggregate.cs
application/CohortManager/src/Functions/CohortDistribution/AggregateDataServices/RemoveFromAggregate/RemoveFromAggregate.csproj
application/CohortManager/src/Functions/CohortDistribution/AggregateDataServices/RemoveFromAggregate/host.json
application/CohortManager/src/Functions/Functions.sln
application/CohortManager/src/Functions/Shared/Common/Interfaces/ICreateAggregationData.cs
application/CohortManager/src/Functions/Shared/Data/Database/CreateAggregationData.cs
scripts/config/gitleaks.toml
tests/AddAggregationDataTests/AggregationDataTests/RemoveAggregateDataTests.cs

adding remove aggregate function
---

feat: adding remove aggregate function

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs
application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/lookupRules.json
application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/StaticValidation.cs
application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/staticRules.json
application/CohortManager/src/Functions/Shared/Common/LookupValidationRequestBody.cs
application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
application/CohortManager/src/Functions/Shared/Data/Database/ICreateParticipantData.cs
application/CohortManager/src/Functions/Shared/Data/Database/UpdateParticipantData.cs
application/CohortManager/src/Functions/screeningDataServices/createParticipant/Program.cs
application/CohortManager/src/Functions/screeningDataServices/createParticipant/createParticipant.cs
tests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs
tests/TestUtils/MockHelpers.cs
tests/screeningDataServicesTests/createParticipantTests/createParticipantTest.cs
tests/screeningDataServicesTests/markParticipantAsEligibleTests/markParticipantAsEligibleTests.cs

Included a call to lookup validation in the create participant function.
[DTOSS-3303](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3303)
---

feat: Added lookup validation to CreateParticipant 

---

application/CohortManager/compose.yaml
application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs

Updated environment variables and fix a couple of incorrect paths in the Docker Compose file.
---

build: Updated Docker Compose environment variables

---

application/CohortManager/src/Functions/screeningDataServices/createParticipant/Program.cs

Added missing dependency injection for ICallFunction in the CreateParticipant class.
Fixes CreateParticipant function bug.
---

fix: Added missing dependency injection in CreateParticipant

---

.azuredevops/cd-infrastructure.yaml
.azuredevops/steps/common/init-validate.yaml
infrastructure/provider.tf

Azure DevOps pipeline trigger and AzureRM provider upgrade
- Azure DevOps Infra CD pipeline should only run when changes are applied to Infrastructure folder.
- upgrade the version of AzureRM provider for further changes and configurations
---

feat: Azure DevOps pipeline trigger and AzureRM provider upgrade

---

application/CohortManager/Set-up/database/create_statement.sql
application/CohortManager/Set-up/database/insert_statement.sql
application/CohortManager/src/Functions/Shared/Common/Interfaces/ICreateCohortDistributionData.cs
application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs
scripts/config/pre-commit.yaml

Removes all hardcoded `cohortId` variables and removes the unused cohort table.
[DTOSS-3522](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3522)
---

feat: remove hardcoded cohortId

---

infrastructure/acr.tf
infrastructure/environments/development.tfvars.config
infrastructure/fnapp.tf
infrastructure/modules/azure-container-registry/main.tf
infrastructure/modules/azure-container-registry/variables.tf
infrastructure/modules/function-app/main.tf
infrastructure/modules/function-app/variables.tf
infrastructure/modules/shared-config/output.tf
infrastructure/variables.tf

This PR includes a terraform code for:
- new set of function apps (DTOSS-3577)
- azure container registry
- new SKU (P2v3) for the app service plan 
- a managed identity for acr (DTOSS-3562) 
---

feat: new version of function apps and azure container registry

---

application/CohortManager/src/Functions/Functions.sln
application/CohortManager/src/Functions/ParticipantManagementServices/RemoveParticipant/RemoveParticipant.cs
application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/Program.cs
application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
application/CohortManager/src/Functions/ParticipantManagementServices/updateParticipant/Program.cs
application/CohortManager/src/Functions/ParticipantManagementServices/updateParticipant/updateParticipant.cs
application/CohortManager/src/Functions/Shared/Common/CallFunction.cs
application/CohortManager/src/Functions/Shared/Common/CohortDistributionHandler.cs
application/CohortManager/src/Functions/Shared/Common/Common.csproj
application/CohortManager/src/Functions/Shared/Common/CreateCohortDistributionRequestBody.cs
application/CohortManager/src/Functions/Shared/Common/Interfaces/ICallFunction.cs
application/CohortManager/src/Functions/Shared/Common/Interfaces/ICohortDistributionHandler.cs
application/CohortManager/src/Functions/screeningDataServices/Properties/launchSettings.json
tests/ParticipantManagementServicesTests/RemoveParticipantTests/RemoveParticipantTests.cs
tests/ParticipantManagementServicesTests/addParticipantTest/AddParticipantTestClass.cs
tests/ParticipantManagementServicesTests/updateParticipantTests/updateParticipantTests.cs
tests/TestUtils/MockHelpers.cs
tests/TestUtils/TestUtils.csproj
tests/tests.sln

1. Update Remove Participant to remove the participant from the CohortDistribution - Calling the Remove from Cohort Service
2. Update AddParticipant to call the Cohort Distribution Service
3. Update UpdateParticipant to call Cohort Distribution Service
4. Tests Updated to check for the above
5. Extended CallFunction to allow gets to be sent with query string from a dictionary of strings as the parameter
[DTOSS-3250](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3250)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull …

feat: call cohort distribution service from AddParticipant, Update Participant and Remove Participant

---

.azuredevops/cd-infrastructure.yaml
infrastructure/apimanagement.tf
infrastructure/environments/development.tfvars.config
infrastructure/modules/api-management/main.tf
infrastructure/modules/api-management/variables.tf
infrastructure/modules/shared-config/output.tf
infrastructure/variables.tf

This PR contains:
- Terraform module for the API Management resource
- An additional condition in the Infra CD Pipeline, that results in running the Plan/Apply stages only if the PL is being run manually from ADO
A change to the Infra CD pipeline mitigates the issue of concurrent pipeline runs blocking the SA Container with the Terraform state file.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate …

feat: an api management terraform module and a Infra CD pipeline condition change 

---

infrastructure/environments/development.tfvars.config

Code changes to deploy two missing function apps: 
- create-cohort-distribution
- retrieve-participant-data
---

feat: missing function apps 

---

infrastructure/environments/development.tfvars.config
infrastructure/fnapp.tf
infrastructure/modules/azure-container-registry/output.tf
infrastructure/modules/function-app/locals.tf
infrastructure/modules/function-app/main.tf
infrastructure/modules/function-app/variables.tf
infrastructure/variables.tf

This PR includes changes made to specific configurations of function apps.
Included changes:
- enviroment variables from compose.yaml
- switch to docker from dotnet
- fnapps identity set to managed identity
- docker images tags implementation
- docker images temporary names
Code tested and implemented on local dev environment, terraform plan [successfully executed](https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=122&view=logs&j=ced2749f-787a-529b-d064-72b5c61df22f&t=a8ef944f-7917-542a-f805-14b39eb0c11c) on DToS environment.
--- …

feat: dtoss-3577 function app configuration

---

infrastructure/environments/development.tfvars.config
infrastructure/fnapp.tf
infrastructure/modules/function-app/locals.tf
infrastructure/modules/function-app/main.tf
infrastructure/modules/function-app/variables.tf
infrastructure/variables.tf

A change in Function Apps deployment:
- automatically construct the name of the expected docker image
- implement a variable to control automatic CI for docker images in Function Apps
Change tested and deployed in local environment, successful terraform validation and plan on the DToS environment.
---

feat: final docker images names and a variable controlling automatic docker CI

---

infrastructure/environments/development.tfvars.config
infrastructure/modules/azure-container-registry/identity.tf
infrastructure/modules/azure-container-registry/main.tf
infrastructure/modules/azure-sql-server/database.tf
infrastructure/modules/azure-sql-server/identity.tf
infrastructure/modules/azure-sql-server/main.tf
infrastructure/modules/azure-sql-server/variables.tf
infrastructure/modules/function-app/main.tf
infrastructure/modules/function-app/output.tf
infrastructure/provider.tf
infrastructure/sqlserver.tf
infrastructure/variables.tf

This PR includes changes to:
- Azure SQL Server:
-- created User Assigned Managed Identity
-- enabled UAMI management for SQL Server
-- added a SQL Contributor role to the UAMI
- Function Apps:
-- enabled System Assigned MI alongside UAMI
-- added outputs for each functions' SAMI ID
- Infrastructure folder "terraform fmt -recursive" formatting
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your …

feat: SQL Server admin group, FNApps SAMI enabled with output for IDs

---

infrastructure/modules/function-app/locals.tf

A fix to the Function Apps urls configuration. From:
- `https://dev-uks-static-validation/api/StaticValidation`
to
- `http://dev-uks-static-validation.azurewebsites.net/api/StaticValidation`
---

fix: missing part of the fnapp urls

---

infrastructure/environments/development.tfvars.config
infrastructure/fnapp.tf
infrastructure/modules/function-app/locals.tf
infrastructure/modules/function-app/main.tf
infrastructure/modules/function-app/variables.tf
infrastructure/variables.tf

This PR includes:
- a new global environment variable for function apps: `"WEBSITES_ENABLE_APP_SERVICE_STORAGE" = "false"`
- a final refactor of the `locals.tf` file, with global function app settings moved to a separate group, and final version of functions apps settings constructed using `merge()` function (to avoid unnecessary repetitions of similar values)
- deletion of some unnecessary commented pieces of code
Change tested and successfully implemented in testing environment.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in …

feat: new variable for fnapps and locals merging

---

application/CohortManager/src/Functions/CohortDistributionServices/RemoveCohortDistributionData/RemoveCohortDistributionData.cs
application/CohortManager/src/Functions/ParticipantManagementServices/RemoveParticipant/RemoveParticipant.cs
tests/ParticipantManagementServicesTests/RemoveParticipantTests/RemoveParticipantTests.cs

- [ x] Refactoring (non-breaking change)
---

feat: renamed function name to match name in solution File

---

infrastructure/environments/development.tfvars.config

This PR disables the automatic processing of new docker images within Function Apps - sets the `DOCKER_ENABLE_CI` flag to `false` across all fnapps.
---

feat: disable the automatic processing of new docker images within Function Apps

---

infrastructure/modules/function-app/locals.tf
infrastructure/modules/function-app/main.tf
infrastructure/modules/function-app/variables.tf

feat: dtoss-3393 update terraform module function app

---

.vscode/tasks.json

- Updates CreateException function task to use new folder structure
- Adds missing cohort distribution functions to allow end to end testing
---

chore: update run all functions task

---

infrastructure/environments/development.tfvars.config
infrastructure/modules/function-app/locals.tf

This PR includes terraform changes to deploy a new function app -  validate cohort distribution record.
---

feat: new function app - validate cohort distribution record

---

infrastructure/appserviceplan.tf
infrastructure/environments/development.tfvars.config
infrastructure/modules/app-service-plan/autoscale.tf
infrastructure/modules/app-service-plan/variables.tf
infrastructure/variables.tf

A custom autoscale policy for the app service plan using user-defined rules based on app metrics, so that the application can automatically scale based on its memory usage.
Instances Limits:
- Minimum: 1
- Maximum: 5
- Default: 1
Rule Scale Out:
- Metric Name: Memory Percentage
- Scale Trigger: > 70%
- Duration: 10 minutes
- Time Gain/Aggregation: Average
- Action: Increase the count by 1
- Cool Down: 5 minutes
Rule Scale In:
- Metric Name: Memory Percentage
- Scale Trigger: < 25%
- Duration: 10 minutes
- Time Gain/Aggregation: Average
- Action: Decrease the count by 1
- Cool Down: 5 minutes
--- …

feat: app service plan autoscale based on memory percentage

---

infrastructure/appinsights.tf
infrastructure/environments/development.tfvars.config
infrastructure/law.tf
infrastructure/modules/app-insights/main.tf
infrastructure/modules/app-insights/variables.tf
infrastructure/modules/log-analytics-workspace/main.tf
infrastructure/modules/log-analytics-workspace/output.tf
infrastructure/modules/log-analytics-workspace/variables.tf
infrastructure/provider.tf
infrastructure/variables.tf

As a part of the DTOSS-3653 issue, Application Insights and Log Analytics Workspace is being redeployed to Audit Dev subscription.
After a successful deployment, the 2nd step will be to switch all the Function Apps from the previous AppInsights and LAW to the new ones.
---

feat: application insights and log analytics workspace deployed in the Audit Dev subscription

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs
application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/StaticValidation.cs
application/CohortManager/src/Functions/Shared/Common/ReadRulesFromBlob.cs

adding logging when getting files form blob for rules validation
---

feat: adding logging when getting files form blob for rules validation

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs
application/CohortManager/src/Functions/Shared/Data/Database/ScreeningServiceData.cs

… adding extra logging
reformatitng sql select statment when getting screening name and adding extra logging
---

fix: reformatitng sql select statment when getting screening name

---

infrastructure/modules/function-app/locals.tf

adding missing ExceptionFunctionURL from Create cohort distribution
---

fix: adding missing ExceptionFunctionURL from Create cohort distribution

---

infrastructure/fnapp.tf

Switch function apps to new reporting resources in Audit Subscription.
---

feat: switch function apps to new reporting resources

---

.vscode/tasks.json

Adds the ValidateCohortDistributionRecord function to the run all functions VS Code task.
---

chore: add ValidateCohortDistributionRecord to run all functions task

---

infrastructure/environments/development.tfvars.config
infrastructure/environments/nft.tfvars.config
infrastructure/fnapp.tf
infrastructure/modules/function-app/main.tf
infrastructure/modules/function-app/variables.tf
infrastructure/provider.tf
infrastructure/variables.tf

This RP includes an infrastructure code change that will connect Azure Function App resources from Dev/NFT/Integration/PreProd subscriptions to Azure Container Registry in Dev subscription.
- included a new provider, always pointing to the Dev subscription
- implemented data objects for ACR and ACR Managed Identity
- replaced Function App ACR connection configuration to always refer to Dev ACR 
- renamed the NFT ACR MIs to include the environment name
- deleted unused variables from the Function Apps module
Test terraform plan successfully run for both, Dev and NFT subscriptions.
--- …

feat: NFT Function Apps connected to DEV ACR

---

.github/workflows/stage-3-build-images.yaml

fix: dtoss 00000 fix the pr message

---

infrastructure/modules/managed-identity/main.tf
infrastructure/modules/managed-identity/output.tf
infrastructure/modules/managed-identity/variables.tf

feat: dtoss 4488 create terraform module for managed identites

---

application/CohortManager/src/Functions/DevOpsTestingService/ControllerTest.py
application/CohortManager/src/Functions/DevOpsTestingService/Dockerfile

feat: testing out the pipeline

---

.github/workflows/stage-3-build-images.yaml
application/CohortManager/src/Functions/DevOpsTestingService/ControllerTest.py
application/CohortManager/src/Functions/DevOpsTestingService/Dockerfile

fix: dtoss 0000 testing container deployment

---

infrastructure/modules/managed-identity/main.tf
infrastructure/modules/managed-identity/output.tf
infrastructure/modules/managed-identity/variables.tf

Re-organise new Managed Identities module to make use of separate RBAC module to perform role assignments.
---

feat: dtoss 4488 create terraform module for managed identities

---

application/CohortManager/rules/Breast_Screening_cohortRules.json
application/CohortManager/rules/Breast_Screening_staticRules.json
application/CohortManager/src/Functions/Shared/Common/CreateParticipant.cs
application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs
application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs
application/CohortManager/src/Functions/Shared/Data/Database/ParticipantManagerData.cs
application/CohortManager/src/Functions/Shared/Model/Participant.cs
tests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs
tests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.cs

- Adds cohort validation rule 67
- Removes static validation rule 58
[DTOSS-3846](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3846)
---

feat: current posting cohort rule 67

---

infrastructure/modules/route-table/main.tf
infrastructure/modules/route-table/output.tf
infrastructure/modules/route-table/variables.tf
infrastructure/test_network.tf

New Terraform module for Route Tables
---

feat: dtoss 4446 create a terraform module for route tables

---

infrastructure/modules/vnet-peering/main.tf
infrastructure/modules/vnet-peering/output.tf
infrastructure/modules/vnet-peering/variables.tf
infrastructure/test_network.tf
infrastructure/test_peering.tf

New Terraform module for VNet Peerings
---

Feat: dtoss 3388 create terraform module for vnet peerings

---

infrastructure/environments/development.tfvars.config
infrastructure/environments/nft.tfvars.config
infrastructure/fnapp.tf
infrastructure/modules/storage/main.tf
infrastructure/modules/storage/output.tf
infrastructure/modules/storage/variables.tf
infrastructure/storage.tf
infrastructure/variables.tf

This PR includes a new way of deploying storage accounts and containers, using for_each and a refactored storage_accounts map in TFVARS files.
The goal of this change is to be able to deploy new storage accounts in the most flexible way.
---

feat: new way of deploying storage accounts and containers

---

.github/workflows/stage-3-build-images.yaml
scripts/deployment/get-docker-names.sh

Update to docker image generation script and pipeline:
- fixed the name of `remove-validation-exception-data` function
- added missing functions to all functions block
- fixed tagging for empty PR number
---

fix: update to docker image generation script and pipeline

---

application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
application/CohortManager/src/Functions/CohortDistributionServices/RetrieveParticipantData/RetrieveParticipantData.cs

feat: adding extra logging to the retrive and add in cohort dist
---

feat: adding extra logging to the retrieve and add in cohort dist

---

application/CohortManager/src/Functions/Shared/Data/Data.csproj

fix: remove validation exception data sql errors

---

application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/StaticValidation.cs

Commented out method for Pipeline
Possibly breaking the PL
- [x ] Refactoring (non-breaking change)
- [x ] Breaking change (fix or feature that would change existing functionality)
- [x ] Bug fix (non-breaking change which fixes an issue)
--- …

fix: commented out method, Refactored to Pascal Case

---

application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/StaticValidation.cs
application/CohortManager/src/Functions/Shared/Data/Database/ValidationExceptionData.cs

removed RemoveOldValidationRecord method and added logging 
Pipeline testing/fixing 
- [ x] Refactoring (non-breaking change)
- [ x] Breaking change (fix or feature that would change existing functionality)
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have followed the code style of the project
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain …

fix: removed RemoveOldValidationRecord method and added logging 

---

.azuredevops/pipelines/cd-infrastructure-int.yaml
infrastructure/environments/integration.tfvars.config

This PR includes initial Integration Environment CD pipeline and TFVars files to do an initial environment rollout.
---

feat: integration environment tfvars and pipeline files

---

infrastructure/environments/nft.tfvars.config

This PR includes a change that enables the Docker CI across the NFT environment.
---

feat: enable Docker CI in NFT environment

---

application/CohortManager/src/Functions/screeningDataServices/DemographicDataService/DemographicDataService.cs
tests/screeningDataServicesTests/DemographicDataServiceTests/demographicDataServiceTests.cs

feat: dtoss 4816 handle invalid type writen to demographic table

---

infrastructure/environments/development.tfvars.config

fix: adding new config values to the config values code

---

infrastructure/environments/nft.tfvars.config

This PR includes changes to update the NFT environment variables for UpdateParticipant function.
---

feat: updating the NFT evnironment variables for UpdateParticipant

---

application/CohortManager/src/Functions/Shared/Common/CallFunction.cs

trival change - removed whitespace 
trival change - removed whitespace to test pipeline 
---
- [ x] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase …

chore: pipeline test

---

.azuredevops/pipelines/generate-owasp-zap-report.yaml
scripts/azure/SlackWebhookController.py
scripts/azure/services/SlackWebhookBot.py
scripts/azure/services/Utilities.py

feat: Add OWASP ZAP report

---

.github/actions/create-lines-of-code-report/action.yaml
.github/actions/scan-dependencies/action.yaml
.github/workflows/stage-1-commit.yaml
.github/workflows/stage-3-build-images.yaml

feat: dtoss 4497 onboard and integrate vulnerability scanning syft and grype for sp repo

---

.github/workflows/stage-3-build-images.yaml
scripts/deployment/get-docker-names.sh

This PR includes changes to the changed functions list script and image building pipeline to run the docker compose tasks using a GitHub matrix (parallel runners). 
Changes tested in dev environment.
---

feat: modify the image creation process into GitHub matrix

---

.azuredevops/pipelines/new_image_triggers_slack_message.yaml
infrastructure/environments/development.tfvars.config
infrastructure/environments/integration.tfvars.config
infrastructure/environments/nft.tfvars.config
scripts/deployment/get-docker-names.sh

The PR includes an infra configuration for the new `retrieve-cohort-request-audit` function.
---

feat: infra configuration for the retrieve-cohort-request-audit function

---

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json
tests/TransformDataServiceTests/TransformDataServiceTests.cs

Changed the email address truncation length from 32 to 90
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-4578
---

fix: email truncation length

---

application/CohortManager/src/Functions/Shared/DataServices.Core/Interfaces/IRequestHandler.cs
application/CohortManager/src/Functions/Shared/DataServices.Core/RequestHandler.cs
application/CohortManager/src/Functions/screeningDataServices/BsSelectGpPractice/BsSelectGpPractice.csproj
application/CohortManager/src/Functions/screeningDataServices/BsSelectGpPractice/BsSelectGpPracticeDataService.cs
application/CohortManager/src/Functions/screeningDataServices/BsSelectGpPractice/Program.cs

feat: the request handler now returns a http response

---

infrastructure/environments/development.tfvars.config
infrastructure/function-app.tf
infrastructure/modules/key-vault/output.tf
infrastructure/variables.tf

In preparation for onboarding Azure Functions that require Key Vault access, a new environment variable is required for use by relevant functions.
---

feat: Add Key Vault URL to Function Apps

---

.azuredevops/pipelines/new_image_triggers_slack_message.yaml
infrastructure/environments/development.tfvars.config
scripts/deployment/get-docker-names.sh

Update new environment variable name from KeyvaultURL to KeyVaultConnectionString in line with function code.
---

feat: Update KeyVaultConnectionString for Mesh Function App

---

.github/workflows/stage-3-build-images.yaml

fix: image Build Issue

---

.github/workflows/stage-2-test.yaml

fix: unit test timeout increase

---

infrastructure/data.tf
infrastructure/function-app.tf

Add KV access control list for Mesh function so secrets can be read
---

feat: DTOSS-3524 Add KV access control list for Mesh function

---

application/CohortManager/src/Functions/Shared/Common/MeshToBlobTransferHandler.cs

updating mesh client to include latest changes
prefix message id on to reassembled chunked message filename 
---

fix: update mesh client and chunked filename issue

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/FileNameParser.cs

fix: filename regex

---

application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/README.md

chore: mesh function documentation

---

infrastructure/function-app.tf

Adding a Key Vault Certificate Get and List permissions for the Mesh Function to already implemented Secret permissions.
---

feat: certificate list and get permissions for mesh function

---

application/CohortManager/Set-up/scripts/csv-to-parquet/csv_to_parquet.py
application/CohortManager/Set-up/scripts/mesh-integation-test-utilities/create_mesh_auth_header.py
application/CohortManager/Set-up/scripts/mesh-integation-test-utilities/send-mesh-file.http
application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/Program.cs
application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFileConfig.cs

- Bug fix for local meshsandbox
- Include Scripts for testing Mesh
---

fix: mesh local problems and testing utilities 

---

application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs
application/CohortManager/src/Functions/Shared/Data/Database/DatabaseHelper.cs

cohort distribution datetime parsing
parsing issue with insert/update  datetime
---

fix: cohort distribution datetime parsing

---

application/CohortManager/rules/Breast_Screening_staticRules.json
application/CohortManager/src/Functions/Shared/Common/ValidationHelper.cs
application/CohortManager/src/Functions/Shared/Model/CohortDistributionParticipant.cs
application/CohortManager/src/Functions/Shared/Model/Participant.cs
tests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.cs

feat: eligibility flag validation based on recordtype

---

application/CohortManager/rules/Breast_Screening_staticRules.json
tests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.cs

feat: DTOSS-5206 Exception raised when Effective Date have invalid Date Format

---

application/CohortManager/rules/Breast_Screening_staticRules.json
tests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.cs

This PR adds custom exception messages to each of the static rules to improve error reporting and debugging.
The aim of this change is to ensure that when  when validation fails for various fields, exception messages are logged. This improves reliability.
---

feat: DTOSS-3909 - Exception List

---

application/CohortManager/src/Functions/ParticipantManagementServices/updateParticipant/Program.cs

making sure that azure queue helper is in the update
---

fix: making sure that azure queue helper is in the update

---

application/CohortManager/src/Functions/CohortDistributionServices/RetrieveCohortDistribution/Program.cs

Adding in missing service for DI
fixed a 500 due to missing service 
---

fix: adding missing service registry

---

.github/workflows/stage-1-commit.yaml

Higher level repository policies appear to have been tightened up and require additional scanning checks to be performed.
---

fix: github dependency scanning fix

---

infrastructure/tf-audit/outputs.tf
infrastructure/tf-core/data.tf
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/function_app.tf
infrastructure/tf-core/locals.tf
infrastructure/tf-core/variables.tf

Changes made to retrieve output from audit tfstatefile to consume the log analytics workspace ID
---

feat: DTOSS 5205 diagnostic settings module fahad

---

application/CohortManager/rules/Breast_Screening_staticRules.json
tests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.cs

fixes to the name validations that were changed in a previous PR
---

fix: name validation fixes

---

infrastructure/tf-core/locals.tf

feat: Simplify locals block to return primary_region
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=5171&view=logs&s=24a0684a-7600-516a-e809-bc6f17e1f6d6 
---

feat: Simplify locals block to return primary_region

---

application/CohortManager/src/Functions/CaasIntegration/processCaasFile/processCaasFile.cs
application/CohortManager/src/Functions/Shared/Common/ExceptionHandler.cs
application/CohortManager/src/Functions/Shared/Common/Interfaces/IExceptionHandler.cs
application/CohortManager/src/Functions/Shared/Common/ProcessCaasFile.cs
application/CohortManager/src/Functions/Shared/Model/Enums/ExceptionCategory.cs

Create Exception when a DEL Record is recieved.
[DTOSS-5381](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5381)
- x ] New feature (non-breaking change which adds functionality)
---

feat: Deleated Record Exception

---

application/CohortManager/compose.yaml
application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
application/CohortManager/src/Functions/Shared/Common/CohortDistributionHandler.cs
application/CohortManager/src/Functions/Shared/Common/ProcessCaasFile.cs

queue names were wrong so the change I am making will allow us to create default queue names and change them if they need to be 
- This Change will require a database refresh to fix the related bug. This fix is a follow on from the other bug fix which changes the length of all dates in the demographic table. 
- Take note that the platform team does not have a way of adding static strings to the functions right now so we will be updating the settings manually after deployment 
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5616
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting- …

fix: now gets queue names from settings

---

infrastructure/tf-audit/environments/integration.tfvars
infrastructure/tf-audit/environments/preprod.tfvars
infrastructure/tf-audit/storage.tf
infrastructure/tf-audit/variables.tf
infrastructure/tf-core/environments/preprod.tfvars

Add a storage account for SQL Server Audit Logging
---

feat: DTOSS-5601 Add Storage Account to Audit subscription

---

infrastructure/tf-core/app_service_plan.tf
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/function_app.tf
infrastructure/tf-core/variables.tf

Add ability to define static string environment variables in the function app config.
---

feat: DTOSS-5710 Add Static Environment Variables to Function Apps

---

application/CohortManager/src/Functions/screeningDataServices/GetValidationExceptions/GetValidationExceptions.cs
infrastructure/tf-core/locals.tf
tests/screeningDataServicesTests/ValidationExceptionDataTests/GetValidationExceptionTests/GetValidationExceptionsTests.cs

removed reference to null object if Id didn't exist 
throwing 500 nullReference 
---

fix: null reference fix if Id does not exist

---

infrastructure/tf-core/environments/preprod.tfvars

Add UpdateParticipant environment queue variable
---

feat: DTOSS-5710 Add UpdateParticipant environment queue variable

---

infrastructure/environments/development.tfvars.config
infrastructure/environments/nft.tfvars.config
infrastructure/function-app.tf
infrastructure/variables.tf

New environmental variables added to functions, along with the functionality of adding static env variables.
receive-caas-file:
- BatchSize=3500
- AddQueueName=add-participant-queue
- recordThresholdForBatching-3
- batchDivisionFactor-5
add-participant:
- CohortQueueName=cohort-distribution-queue
- AddQueueName=add-participant-queue
create-cohort-distribution:
- CohortQueueName=cohort-distribution-queue
- CohortQueueNamePoison=cohort-distribution-queue-poison
update-participant:
- CohortQueueName=cohort-distribution-queue
transform-data-service:
- ExceptionFunctionURL
- DtOsDatabaseConnectionString
Successful plans on:
- dev:
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=6396&view=logs&j=ced2749f-787a-529b-d064-72b5c61df22f&t=a8ef944f-7917-542a-f805-14b39eb0c11 …

feat: new env variables for few functions

---

application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformAction.cs
application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json
application/CohortManager/src/Functions/Shared/Common/ExceptionHandler.cs
application/CohortManager/src/Functions/Shared/Common/ReceiveCaasFileHelper.cs
tests/CohortDistributionTests/CreateCohortDistributionTests/CreateCohortDistributionTests.cs
tests/TransformDataServiceTests/TransformDataServiceTests.cs

issue where dates where not being transformed by the transform rules
---

fix: date transform issue

---

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/namePrefixRules.json

- bug where REV, RT REV, and FR were transformed incorrectly
[DTOSS-5814](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5814)
[DTOSS-5804](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5804)
---

fix: name prefix bug

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/ProcessFileClasses/ProcessCaasFile.cs
application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
application/CohortManager/src/Functions/Shared/Common/Interfaces/IReceiveCaasFileHelper.cs
application/CohortManager/src/Functions/Shared/Common/ReceiveCaasFileHelper.cs
application/CohortManager/src/Functions/Shared/Data/Database/ParticipantManagerData.cs

fix: date time validation fix

---

.azuredevops/pipelines/cd-infrastructure-int-audit.yaml
.azuredevops/pipelines/cd-infrastructure-int-core.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-audit.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-core.yaml

Updating commit reference in pipeline yaml
---

feat: DTOS 5205 updating commit reference in pipeline yaml

---

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformString.cs
tests/TransformDataServiceTests/TransformDataServiceTests.cs

Fixes underscore characters not transforming.
[DTOSS-5842](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5842)
---

fix: underscore transformations

---

application/CohortManager/rules/Breast_Screening_staticRules.json
application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/Breast_Screening_staticRules.json
tests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.cs

fix: making sure elibigity flag is correct

---

.azuredevops/pipelines/cd-infrastructure-int-audit.yaml
.azuredevops/pipelines/cd-infrastructure-int-core.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-audit.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-core.yaml
infrastructure/tf-audit/storage.tf
infrastructure/tf-core/rbac.tf
infrastructure/tf-core/storage.tf

Variable structure change to accommodate the latest Storage module version (it's a simplification).
Tested [here](https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=7554&view=logs&j=ced2749f-787a-529b-d064-72b5c61df22f&t=a8ef944f-7917-542a-f805-14b39eb0c11c) resulting in a successful Terraform plan, changes to diagnostic settings are unrelated, from test deployments from another branch)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR …

fix: Storage module RBAC roles variable format change

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/host.json

fix: update host logging level

---

application/CohortManager/rules/Breast_Screening_staticRules.json
application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_lookupRules.json
application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/Breast_Screening_staticRules.json
application/CohortManager/src/Functions/screeningDataServices/updateParticipantDetails/Program.cs
application/CohortManager/src/Functions/screeningDataServices/updateParticipantDetails/updateParticipantDetails.cs

…e not run as code. Fix: fixing: ParticipantLocationRemainingOutsideOfCohort. Feat: Now gets histroical data from cohort table for participant
Fix: updating outer expressions on rules to make sure that outputs are not run as code. 
Fix: fixing: ParticipantLocationRemainingOutsideOfCohort. 
Feat: Now gets historical data from cohort table for participant
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really …

fix: fixing rules making sure that update can get through to cohort

---

application/CohortManager/rules/Breast_Screening_staticRules.json
application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/Breast_Screening_staticRules.json
application/CohortManager/src/Functions/Shared/Common/ReceiveCaasFileHelper.cs
tests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.cs

Change eligibility flag bool back to bit so It can insert in to the database.
---

fix: eligbility flag null fix

---

infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/preprod.tfvars

Add ExceptionFunctionURL to additional functions in Integration and Pre Prod environments
---

fix: Add ExceptionFunctionURL to additional functions

---

infrastructure/tf-audit/diagnostic_settings.tf
infrastructure/tf-audit/locals.tf
infrastructure/tf-audit/log_analytics_workspace.tf
infrastructure/tf-audit/networking.tf
infrastructure/tf-audit/private_link_scopes.tf
infrastructure/tf-audit/storage.tf

Fixes for Diagnostics Settings across Hub, Audit and the Templates repo.
---

feat: DTOSS-5205 Configure Audit Diagnostic Settings

---

application/CohortManager/src/Functions/CohortDistributionServices/RetrieveCohortDistribution/RetrieveCohortDistribution.cs
application/CohortManager/src/Functions/CohortDistributionServices/RetrieveCohortReplay/RetrieveCohortReplay.cs
application/CohortManager/src/Functions/screeningDataServices/GetValidationExceptions/GetValidationExceptions.cs

removed post method from functions signatures
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6014
Removed post methods from function signature 
Used nameOf for function name 
---

feat: removed post method from functions signatures

---

application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs
application/CohortManager/src/Functions/Shared/Data/Database/DatabaseHelper.cs

Incorrect date format on response object so changed to match schema 
Format changed to return string in ccyyMMdd format for date properties 
---

feat: Date format changed to match API schema

---

.azuredevops/pipelines/cd-infrastructure-int-audit.yaml
.azuredevops/pipelines/cd-infrastructure-int-core.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-audit.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-core.yaml
infrastructure/tf-audit/private_link_scopes.tf
infrastructure/tf-audit/rbac.tf
infrastructure/tf-audit/storage.tf
infrastructure/tf-core/function_app.tf
infrastructure/tf-core/key_vault.tf
infrastructure/tf-core/rbac.tf
infrastructure/tf-core/sql_server.tf
infrastructure/tf-core/storage.tf
infrastructure/tf-core/variables.tf

Technical debt reduction:
- Refactor of private DNS code
- Simplification of `function_app.tf`
- Switch Key Vault to RBAC authentication mode, since Access Policies will be blocked by policy organisation-wide.
Successful deployment to Integration Audit: https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=8551&view=results
Successful deployment to Integration Core: https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=8564&view=results
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this …

fix: non-live DNS zone name and private DNS tidy

---

infrastructure/tf-core/environments/preprod.tfvars

Following the re-factor of the `function-app.tf`, the structure of the static environment variables for each Function App has been simplified to be easier to merge with the other env vars.
Successfully deployed to:
- Pre-Prod Audit: https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=8772&view=results
- Pre-Prod Core: https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=8778&view=results
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We …

fix: variable typing fix for refactored function_app.tf

---

application/CohortManager/src/Functions/screeningDataServices/BsSelectGpPractice/BsSelectGpPracticeDataService.cs
application/CohortManager/src/Functions/screeningDataServices/BsSelectOutCode/BsSelectOutCodeDataService.cs
application/CohortManager/src/Functions/screeningDataServices/CurrentPostingDataService/CurrentPostingDataService.cs
application/CohortManager/src/Functions/screeningDataServices/LanguageCodesDataService/LanguageCodesDataService.cs

url for data service needed changing to support the terrafrom method of creating links to other functions 
---

fix: data services url

---

application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceClient.cs
application/CohortManager/src/Functions/screeningDataServices/ExcludedSMULookupDataService/ExcludedSMULookupDataServices.cs

Bug fixes for data services
- Adding proper url for excluded SMU Data Service
- Null Handling for Filter Expressions
---

fix: null filter response handling, adding url to excluded SMU

---

application/CohortManager/src/Functions/screeningDataServices/LanguageCodesDataService/LanguageCodesDataService.cs

fix: language codes url

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/host.json
application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceClient.cs

fix: update logging on lookup and fix url builder issue

---

application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs

204 status code to write to audit table
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6118
currently 200 is being sent to the audit table instead of 204
---

fix: 204 to write to audit table

---

.azuredevops/pipelines/new_image_triggers_slack_message.yaml
infrastructure/environments/development.tfvars.config
infrastructure/environments/nft.tfvars.config
scripts/deployment/get-docker-names.sh

Removal of the remains of two unused functions:
- Remove Cohort Distribution Data 
- Process Caas File
Mirroring changes from this PR to `main` branch: https://github.com/NHSDigital/dtos-cohort-manager/pull/425
Successful plan on Dev:
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=9141&view=logs&j=ced2749f-787a-529b-d064-72b5c61df22f&t=a8ef944f-7917-542a-f805-14b39eb0c11c
Successful plan on NFT:
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=9142&view=logs&j=ced2749f-787a-529b-d064-72b5c61df22f&t=a8ef944f-7917-542a-f805-14b39eb0c11c
--- …

chore: remove unused functions and function apps

---

application/CohortManager/src/Functions/CohortDistributionServices/RetrieveCohortRequestAudit/RetrieveCohortRequestAudit.cs
application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs

fix: Cohort Audit fix and updated error messages 
now writes 204 to audit table and updated the error messages 
---

fix: Cohort Audit fix and updated error messages 

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/ProcessFileClasses/ProcessCaasFile.cs
application/CohortManager/src/Functions/Shared/Common/ExceptionHandler.cs
application/CohortManager/src/Functions/Shared/Common/Interfaces/IExceptionHandler.cs
application/CohortManager/src/Functions/Shared/Model/Enums/ExceptionCategory.cs

Invalid record types now log to exception table
[DTOSS-6060](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6060)
---

fix: add exception log for invalid record type

---

application/CohortManager/src/Functions/Shared/Model/Enums/FatalRule.cs
application/CohortManager/src/Functions/Shared/Model/ValidateCohortDistributionRecordBody.cs
application/CohortManager/src/Functions/screeningDataServices/BsSelectOutCode/BsSelectOutCodeDataService.cs
application/CohortManager/src/Functions/screeningDataServices/CurrentPostingDataService/CurrentPostingDataService.cs
application/CohortManager/src/Functions/screeningDataServices/ExcludedSMULookupDataService/ExcludedSMULookupDataServices.cs
application/CohortManager/src/Functions/screeningDataServices/LanguageCodesDataService/LanguageCodesDataService.cs
application/CohortManager/src/Functions/screeningDataServices/createParticipant/createParticipant.cs
application/CohortManager/src/Functions/screeningDataServices/markParticipantAsEligible/markParticipantAsEligible.cs

Resolving all the bugs generated by SonarQube.
Please find below the SonarQube link have the bug details:
https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&types=BUG&id=NHSDigital_dtos-cohort-manager
---

feat: DTOSS-6233 SonarQube Fix

---

application/CohortManager/src/Functions/Shared/Common/CohortDistributionHelper.cs

Fixed an error where the exception table was not being updated if transformDataService returned null.
---

fix: Logs error when transformDataService returns null

---

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformString.cs

Resolving all the bugs generated by SonarQube.
Please find below the SonarQube link have the bug details:
https://sonarcloud.io/project/security_hotspots?id=NHSDigital_dtos-cohort-manager
---

feat: DTOSS 6241 sonarqube fixes

---

.azuredevops/pipelines/cd-infrastructure-int-audit.yaml
.azuredevops/pipelines/cd-infrastructure-int-core.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-audit.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-core.yaml
infrastructure/tf-audit/environments/integration.tfvars
infrastructure/tf-audit/environments/preprod.tfvars
infrastructure/tf-audit/log_analytics_workspace.tf
infrastructure/tf-audit/variables.tf
infrastructure/tf-core/environments/preprod.tfvars

Updates to previous configuration of the Dev and Prod event hubs to match final requirements - no Event hub required in Dev Hub, point log export to specific Event Hub, not just an EvH Namespace.
---

fix: dtoss 5996 add identity block consumer groups

---

application/CohortManager/src/Functions/CohortDistributionServices/RetrieveCohortDistribution/RetrieveCohortDistribution.cs
application/CohortManager/src/Functions/CohortDistributionServices/RetrieveCohortReplay/RetrieveCohortReplay.cs
application/CohortManager/src/Functions/Shared/Common/Interfaces/ICreateCohortDistributionData.cs
application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs
tests/UnitTests/CohortDistributionTests/CohortDistributionDataTests/AddCohortDistributionTests.cs

SQL change on WHERE clause,  
rowCount added to methods 
Order by added to request_audit table 
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6242
Fix - it was returning all records with a later created date than the one passed in, ignoring requestIds and rowCount 
---

fix: Retrieve Cohort Distribution SQL syntax 

---

application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceClient.cs
application/CohortManager/src/Functions/Shared/DataServices.Client/IDataServiceClient.cs
application/CohortManager/src/Functions/Shared/DataServices.Core/DataServiceAccessor.cs
application/CohortManager/src/Functions/Shared/DataServices.Core/Interfaces/IDataServiceAccessor.cs
application/CohortManager/src/Functions/Shared/DataServices.Core/RequestHandler.cs
tests/DataServiceTests/BsSelectGpPracticeDataServiceTests.cs
tests/DataServiceTests/BsSelectOutCodeDataServiceTests.cs
tests/DataServiceTests/MockDataServiceAccessor.cs

Extending the capability of data services to allow for multiple records to be inserted at one when called with an array.
---

feat: code changes to enable multiple records post to dataservices

---

.azuredevops/pipelines/cd-infrastructure-int-audit.yaml
.azuredevops/pipelines/cd-infrastructure-int-core.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-audit.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-core.yaml
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/sql_server.tf
infrastructure/tf-core/variables.tf

Configuration to change the redundancy option to 'Local', for DB backup storage
---

feat: dtoss 0000 local backup storage option

---

application/CohortManager/src/Functions/Shared/Common/Pagination/IPaginationService.cs
application/CohortManager/src/Functions/Shared/Common/Pagination/PaginationResult.cs
application/CohortManager/src/Functions/Shared/Common/Pagination/PaginationService.cs
application/CohortManager/src/Functions/Shared/Data/Database/ValidationExceptionData.cs
application/CohortManager/src/Functions/screeningDataServices/GetValidationExceptions/GetValidationExceptions.cs
application/CohortManager/src/Functions/screeningDataServices/GetValidationExceptions/Program.cs
tests/UnitTests/ScreeningDataServicesTests/ValidationExceptionDataTests/GetValidationExceptionTests/GetValidationExceptionsTests.cs

Created Pagination Service and implemented it in ValdiationException 
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6059
Front end can use pagination for exceptions 
---

feat: Pagination Service 

---

.azuredevops/pipelines/cd-infrastructure-int-audit.yaml
.azuredevops/pipelines/cd-infrastructure-int-core.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-audit.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-core.yaml
infrastructure/tf-audit/environments/integration.tfvars
infrastructure/tf-audit/environments/preprod.tfvars
infrastructure/tf-audit/log_analytics_workspace.tf
infrastructure/tf-audit/variables.tf

Final changes to event hub config following client conversation
---

feat: dtoss 5997 amend eventhub config

---

application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs

error thrown when SQL query was being built 
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6380
Exceptions being thrown by incorrect syntax. fixed by reordering sql query 
---

feat: query params throwing error

---

application/CohortManager/src/Functions/CohortDistributionServices/RetrieveCohortDistribution/RetrieveCohortDistribution.cs
application/CohortManager/src/Functions/Shared/Common/Interfaces/ICreateCohortDistributionData.cs
application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs

refactored RetrieveCohortDistributionData to remove rows and handle single requestID
No ticket assigned to PR
Not as user expected, rowCount removed and all requests for single requestId now returned 
---

feat: refactored RetrieveCohortDistributionData

---

application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs

RequestId changing value
pulling multiple requestIds
---

fix: requestId fix 

---

application/CohortManager/src/Functions/Shared/Common/CallFunction.cs
application/CohortManager/src/Functions/Shared/Common/Interfaces/ICallFunction.cs
application/CohortManager/src/Functions/Shared/Common/Utilities/ReflectionUtilities.cs
application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceClient.cs
application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceClientBuilder.cs
application/CohortManager/src/Functions/Shared/DataServices.Core/RequestHandler.cs
tests/DataServiceTests/DataServiceClientTests.cs
tests/TestUtils/MockHelpers.cs

- Added new method to Data Service Client to facilitate update requests
- Added new SendPut Methods to CallFunction
- Moved Logic for getting the Key of a EF object to a generic static class 
- Added Unit tests for Data Service Client
- Added Mock Web Exception Utilities to test classes
- Added Null check for Data Service URL for more obvious logging
[DTOSS_6457](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6457)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR …

feat: add update function to Data Services client

---

application/CohortManager/src/Functions/Shared/DataServices.Core/RequestHandler.cs

Urgent fix for broken data services.
---

fix: missing reference to common

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs

Adding logging for lookup validation to debug the rule 51 issue
---

fix: enhanced logging for lookup validation

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs

fix: temp rule logging

---

application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
application/CohortManager/src/Functions/Shared/Data/Database/CreateDemographicData.cs
application/CohortManager/src/Functions/Shared/Data/Database/DatabaseHelper.cs
application/CohortManager/src/Functions/Shared/Data/Database/IDatabaseHelper.cs
application/CohortManager/src/Functions/Shared/Model/Constants/DataTypes.cs
tests/UnitTests/CohortDistributionTests/CreateCohortDistributionTests/CreateCohortDistributionTests.cs

Add tests to increase code coverage - 97.89%
Refactored methods to adhere to DRY standards. 
Added Tests 
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6413
---

feat: CreateCohortDistribution code coverage

---

application/CohortManager/src/Functions/CohortDistributionServices/AddCohortDistributionData/AddCohortDistributionData.cs
application/CohortManager/src/Functions/CohortDistributionServices/ServiceProviderAllocationService/AllocateServiceProviderToParticipantByService.cs
application/CohortManager/src/Functions/ScreeningValidationService/RemoveValidationException/RemoveValidationExceptionData.cs

Fixes 3 minor sonar qube reliability issues ("Logging arguments should be passed to the correct parameter"):
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED&open=AZIu6j7CfqqoiTammAvd
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED&open=AZIu6j6sfqqoiTammAva
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED&open=AZIu6j9NfqqoiTammAv7
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We …

fix: sonar qube reliability logging issues

---

application/CohortManager/compose.core.yaml
application/CohortManager/src/Functions/Shared/DataServices.Database/DataServicesContext.cs
application/CohortManager/src/Functions/Shared/Model/EFModels/GeneCodeLkp.cs
application/CohortManager/src/Functions/Shared/Model/EFModels/HigherRiskReferralReasonLkp.cs
application/CohortManager/src/Functions/screeningDataServices/GeneCodeLkpDataService/Dockerfile
application/CohortManager/src/Functions/screeningDataServices/GeneCodeLkpDataService/GeneCodeLkpDataService.cs
application/CohortManager/src/Functions/screeningDataServices/GeneCodeLkpDataService/GeneCodeLkpDataService.csproj
application/CohortManager/src/Functions/screeningDataServices/GeneCodeLkpDataService/Program.cs
application/CohortManager/src/Functions/screeningDataServices/GeneCodeLkpDataService/Properties/launchSettings.json
application/CohortManager/src/Functions/screeningDataServices/GeneCodeLkpDataService/host.json
application/CohortManager/src/Functions/screeningDataServices/HigherRiskReferralReasonLkpDataService/Dockerfile
application/CohortManager/src/Functions/screeningDataServices/HigherRiskReferralReasonLkpDataService/HigherRiskReferralReasonLkpDataService.cs
application/CohortManager/src/Functions/screeningDataServices/HigherRiskReferralReasonLkpDataService/HigherRiskReferralReasonLkpDataService.csproj
application/CohortManager/src/Functions/screeningDataServices/HigherRiskReferralReasonLkpDataService/Program.cs
application/CohortManager/src/Functions/screeningDataServices/HigherRiskReferralReasonLkpDataService/Properties/launchSettings.json
application/CohortManager/src/Functions/screeningDataServices/HigherRiskReferralReasonLkpDataService/host.json

New data services for the GENE_CODE_LKP and HIGHER_RISK_REFERRAL_REASON_LKP tables for the analyse work
These data services are needed as a prerequisite for this ticket: [DTOSS-4707](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-4707)
---

feat: new data services

---

application/CohortManager/src/Functions/screeningDataServices/createParticipant/createParticipant.cs
tests/UnitTests/ScreeningDataServicesTests/CreateParticipantTests/CreateParticipantTest.cs

chore: adding more tests to create better code coverage of create
---

chore: adding more tests to create better code coverage of create

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/ProcessFileClasses/AddBatchToQueue.cs
application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/ProcessFileClasses/ProcessCaasFile.cs
application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/Program.cs
application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/Program.cs
application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/Program.cs
application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
application/CohortManager/src/Functions/ParticipantManagementServices/updateParticipant/Program.cs
application/CohortManager/src/Functions/Shared/Common/AzureQueueStorageHelper.cs
application/CohortManager/src/Functions/Shared/Common/Extensions/AzureQueueExtension.cs
tests/UnitTests/CohortDistributionTests/CreateCohortDistributionTests/CreateCohortDistributionTests.cs

- Add Batch to queue change to use azure Queue Helper (Base64 Decode Issue)
- Use IRecordsTracker Interface on DI
- Negate Ignore Records Flag when it needs to be false
- Use AzureQueue Extension for DI
- Fixes Base64 decode issue in AddParticipant
- Fixes DI resolution of IRecordsTracker
- Fixes Ignore Flag not working
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this …

fix: ignore exception flags issue and other fixes

---

tests/UnitTests/CaasIntegrationTests/AddBatchToQueueTest/AddBatchToQueueTest.cs

fix: fix add batch to queue tests

---

application/CohortManager/src/Functions/Shared/Model/Mapping/ParticipantsParquetMap.cs

Fixes sonarqube issues in `ParticipantsParquetMap` file.
https://sonarcloud.io/project/issues?rules=csharpsquid%3AS1104&id=NHSDigital_dtos-cohort-manager
---

fix: sonarqube participant parquet map issues

---

application/CohortManager/src/Functions/Shared/DataServices.Core/DataServiceAccessor.cs

Exception handling around the dataservice
Exception Handling 
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6291
---

fix: DataService exception handling

---

application/CohortManager/src/Functions/CohortDistributionServices/RetrieveCohortDistribution/RetrieveCohortDistribution.cs
application/CohortManager/src/Functions/Shared/Common/HttpParserHelper.cs
application/CohortManager/src/Functions/Shared/Common/Interfaces/IHttpParserHelper.cs
application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs

Bug fix, removed duplicate code and refactor helper class
functionality not working as expected, this should resolve
---

fix: retreive cohort bug fixes 

---

application/CohortManager/src/Functions/Shared/Data/Database/CreateDemographicData.cs
application/CohortManager/src/Functions/Shared/Data/Database/ICreateDemographicData.cs
application/CohortManager/src/Functions/Shared/Data/Database/ScreeningServiceData.cs
application/CohortManager/src/Functions/Shared/Data/Database/ValidationExceptionData.cs

Fixes "Make 'AddParameters' a static method." in all affected files.
Fixes some other minor issues I found within the affected files, including removing a redundant logger from ScreeningServiceData.
https://sonarcloud.io/project/issues?assignees=andrewmorris43-O33LS%40github&impactSeverities=LOW&impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=NHSDigital_dtos-cohort-manager
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain …

fix: more sonarqube issues

---

application/CohortManager/src/Functions/Shared/Common/CallFunction.cs

Adding details of call to error message for call function.
Moved GetResponseText to above private methods as the methods was public.
easier error debugging
---

feat: extra logging to call function

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_lookupRules.json
tests/UnitTests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs

feat: Rule 36 exception thrown due to SMU

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_cohortRules.json
application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_lookupRules.json
tests/UnitTests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs

Updated tests and logic around rule 51
Fix Broken rule 36
[DTOSS-6291](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6291)
---

fix: rule 51

---

.azuredevops/pipelines/acr-image-promote-dev-to-nft.yaml
.azuredevops/pipelines/acr-image-promote-nft-to-integration.yaml
.azuredevops/pipelines/acr-image-retag.yaml
.azuredevops/pipelines/post-deployment-tests-dev.yaml

New ADO pipeline to transfer Docker images across container registries, including image tags for PR numbers and git commit refs.
Until we've fully moved Dev and NFT over to the Dev Hub ACR instead of the local Dev ACR, we will still need to use the existing script to complete the NFT -> Integration step, but this PL then does the rest, including bringing over the PR and Commit ref tags.
A stand-alone PL template for the post-deployment automation tests is also included as an initial starting point for the automation test developers to build out from.
--- …

feat: New pipeline to retag images

---

application/CohortManager/src/Functions/Shared/Common/ExceptionHandler.cs
application/CohortManager/src/Functions/Shared/Common/Interfaces/IExceptionHandler.cs

Moved the exception handler comments to the interface so they integrate with vscode 
---

chore: move exception handler comments to interface

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/ProcessFileClasses/ValidateDates.cs
application/CohortManager/src/Functions/screeningDataServices/GetValidationExceptions/GetValidationExceptions.cs
tests/UnitTests/CaasIntegrationTests/ValidateDates/ValidateDatesTests.cs

fix: sonar cloud issues

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs
application/CohortManager/src/Functions/DemographicServices/DemographicDataManagementFunction/DemographicDataFunction.cs

This PR is against useless variables issues caught by SonarQube .
https://sonarcloud.io/project/issues?open=AZMqKeQfd-QLy2mXLjD6&id=NHSDigital_dtos-cohort-manager
https://sonarcloud.io/project/issues?open=AZQnnXJOVnPjjIsHHaAI&id=NHSDigital_dtos-cohort-manager
---

fix: address sonarcube issue to remove unless local variables

---

application/CohortManager/Set-up/scripts/mesh-integation-test-utilities/create_mesh_auth_header.py
application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs
application/CohortManager/src/Functions/screeningDataServices/markParticipantAsIneligible/markParticipantAsIneligible.cs

Fixed three small issues
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED&open=AZK9ogbnlaPbon5gMDLP
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED&open=AZMqKeQfd-QLy2mXLjD7
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED&open=AZIu6kA3fqqoiTammAxW
---

fix: Fixed 3 Sonarqube issues

---

application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFile.cs

https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED&open=AZKasL5jRBDKSks71zzp
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED&open=AZKasL5jRBDKSks71zzq
---

fix: Fix logging issues in RetrieveMeshFile

---

application/CohortManager/Set-up/scripts/mesh-integation-test-utilities/create_mesh_auth_header.py
application/CohortManager/src/Functions/Shared/Common/Extensions/ConfigurationExtension.cs
application/CohortManager/src/Functions/Shared/Data/Database/CreateParticipantData.cs

Removed commented out code in create_mesh_auth_header.py
Removed unused variable in ConfigurationExtension.cs
Removed unused variable in CreateParticipantData.cs
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED&open=AZK9ogbnlaPbon5gMDLQ
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED&open=AZKasLwnRBDKSks71zzh
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED&open=AZIu6j9qfqqoiTammAwQ
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any …

fix: Three more fixes for Sonarqube

---

.github/actions/create-lines-of-code-report/action.yaml
.github/actions/scan-dependencies/action.yaml

Update the GitHub Action workflow configurations to use version 4 (v4) to ensure compatibility with the latest features and fixes, as version 3 (v3) is now deprecated
---

feat: DTOS 6981 Updating github action from v3 and v4

---

application/CohortManager/src/Functions/Shared/Common/CreateResponse.cs

https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&id=NHSDigital_dtos-cohort-manager&open=AZIu6j-ufqqoiTammAwt
---

fix: sonarqube match interface param name

---

application/CohortManager/src/Functions/screeningDataServices/ExcludedSMULookupDataService/Program.cs
application/CohortManager/src/Functions/screeningDataServices/ParticipantManagementDataService/Program.cs

Unused variable issue is caught in sonar cloud. This PR is to solve this issue.
For more details, please refer:-
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED
https://sonarcloud.io/issues?issueStatuses=OPEN%2CCONFIRMED
---

fix: sonarqube issue remove unused variable in authconfig

---

application/CohortManager/src/Functions/Shared/Data/Database/ValidationExceptionData.cs
application/CohortManager/src/Functions/Shared/Model/ExceptionDetails.cs

Added Gender property to API response
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6747
---

feat: Added Gender to response

---

.azuredevops/pipelines/cd-infrastructure-dev-audit.yaml
.azuredevops/pipelines/cd-infrastructure-dev-core.yaml
.azuredevops/pipelines/cd-infrastructure-int-audit.yaml
.azuredevops/pipelines/cd-infrastructure-int-core.yaml
.azuredevops/pipelines/cd-infrastructure-nft-audit.yaml
.azuredevops/pipelines/cd-infrastructure-nft-core.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-audit.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-core.yaml
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/function_app.tf
infrastructure/tf-core/variables.tf

Code change to enabling health checks for function apps when a Health probe path is added to the tfvars
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=13649&view=logs&j=c970d263-77bb-52d7-1861-5b2637d7126d&t=c970d263-77bb-52d7-1861-5b2637d7126d
---

feat: dtoss 6910 enabling health checks for function apps

---

application/CohortManager/src/Functions/Shared/DataServices.Client/IDataServiceClient.cs
application/CohortManager/src/Functions/Shared/DataServices.Core/DataServiceAccessor.cs

Update method on data service was not working as expected.
Fix bugs and add Update to Interface
---

fix: update data service bug fix

---

application/CohortManager/compose.core.yaml

Docker file had incorrect ENV Variables.
---

fix: docker file issues

---

scripts/config/gitleaks.toml

Update smoke-test file exclusions so false positives are not created.
- [ 
- ] I have followed the code style of the project
---

fix: Update smoke-test file exclusions

---

.azuredevops/pipelines/post-deployment-tests-dev.yaml
.azuredevops/templates/steps/run-post-deployment-tests.yaml

Provide an evaluation pipeline for the QA Automation engineers to be able to deploy and run their smoke tests prior to merging the changes into an end-to-end pipeline process.
---

feat: dtoss-3350 cd pipeline smoke test evaluation pipeline

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/nft.tfvars

Fixed the static url variable after renaming the function.
Before:
```
DemographicURI = "https://dev-uks-durable-demographic-data-service.azurewebsites.net/api/DurableDemographicFunction_HttpStart/"
GetOrchestrationStatusURL  = "https://dev-uks-durable-demographic-data-service.azurewebsites.net/api/GetOrchestrationStatus"
```
After:
```
DemographicURI = "https://dev-uks-durable-demographic-function.azurewebsites.net/api/DurableDemographicFunction_HttpStart/"
GetOrchestrationStatusURL  = "https://dev-uks-durable-demographic-function.azurewebsites.net/api/GetOrchestrationStatus"
```
--- …

fix: fixed the static url variable after renaming the function

---

application/CohortManager/compose.cohort-distribution.yaml
application/CohortManager/compose.core.yaml

fix: docker config issues

---

infrastructure/tf-core/environments/development.tfvars

Change Dev database scaling to support performance testing.
---

fix: change Dev database scaling

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/ProcessFileClasses/ProcessCaasFile.cs
application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/ProcessFileClasses/ValidateDates.cs
application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
application/CohortManager/src/Functions/ParticipantManagementServices/updateParticipant/updateParticipant.cs
application/CohortManager/src/Functions/ScreeningValidationService/RemoveValidationException/RemoveValidationExceptionData.cs
application/CohortManager/src/Functions/screeningDataServices/createParticipant/createParticipant.cs
application/CohortManager/src/Functions/screeningDataServices/markParticipantAsEligible/markParticipantAsEligible.cs
application/CohortManager/src/Functions/screeningDataServices/markParticipantAsIneligible/markParticipantAsIneligible.cs
application/CohortManager/src/Functions/screeningDataServices/updateParticipantDetails/updateParticipantDetails.cs

We need to...
Remove any development logs and comments that contain any Personal Identifiable Information. This includes NHS numbers. 
[DTOSS-7088](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7088)
Removing sensitive data from development logs while coding is crucial to protect user privacy and security by preventing accidental leaks of confidential information like passwords, credit card details, or personal identifiers, which could be accessed by unauthorized individuals if the logs are ever shared or exposed in a breach, potentially causing significant harm to users and the system. 
--- …

feat: DTOSS-7088-remove any-PII-from-development-logs

---

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json
application/CohortManager/src/Functions/Shared/Common/CreateParticipant.cs
application/CohortManager/src/Functions/Shared/Data/Database/BsTransformationLookups.cs
application/CohortManager/src/Functions/Shared/Data/Database/IBsTransformationLookups.cs
application/CohortManager/src/Functions/Shared/Model/CohortDistributionParticipant.cs
tests/UnitTests/TransformDataServiceTests/TransformDataServiceTests/TransformDataServiceTests.cs

- Remove ParticipantIsInvalid from the BSTransformlookup
- Add InvalidFlag to the CohortDistributionDataModel
- Change rule to check against model.
[DTOSS-7190](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7190)
---

feat: invalid flag transform refactor

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/host.json

Updating the logging setting on LookupValidation for improved performance monitoring 
---

feat: adding depedancy tracking to LookupValidation

---

application/CohortManager/Set-up/database/create_statement.sql

We need to...
Create New Indexes on the DToS Db
[DTOSS-7237](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7237)
In order for...
Us to improve the performance of the database
To...
Ensure the database is behaving in the most optimal way.
---

feat: DTOSS-7237 create indexes in cohortmanager database

---

application/CohortManager/compose.cohort-distribution.yaml
application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/Program.cs
application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataServiceConfig.cs
application/CohortManager/src/Functions/Shared/Data/Database/BsTransformationLookups.cs

Use Data Services rather than direct DB call for Getting BSO code from PCP
[DTOSS-7166](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7166)
---

feat: Move GetBsoCodeUsingPCP to DataServices

---

infrastructure/tf-core/environments/development.tfvars

Data service missing env variable 
---

fix: missing env variable

---

infrastructure/tf-core/environments/development.tfvars

retrieve participant had the wrong Data Function env variable
Broken dev
---

fix: incorrect env variable fix

---

application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceClient.cs

Fixes bug where not found would cause a json deserialise exception.
---

fix: get single fix

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars

A fix for DemographicDataManagement with the ParticipantDemographicDataService variable for Dev and NFT.
---

fix: a fix for DemographicDataManagement with the ParticipantDemographicDataService variable for Dev and NFT

---

application/CohortManager/src/Functions/ParticipantManagementServices/updateParticipant/Program.cs
application/CohortManager/src/Functions/Shared/Model/Participant.cs
application/CohortManager/src/Functions/screeningDataServices/updateParticipantDetails/Program.cs
application/CohortManager/src/Functions/screeningDataServices/updateParticipantDetails/updateParticipantDetails.cs

fix: maing sure update is parsing and updating all data
---

fix: maing sure update is parsing and updating all data

---

application/CohortManager/src/Functions/Shared/Common/CallFunction.cs
application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceClient.cs
application/CohortManager/src/Functions/Shared/DataServices.Core/DataServiceAccessor.cs

fix: adding logging to debug

---

.azuredevops/pipelines/post-deployment-tests-dev.yaml
.azuredevops/templates/steps/run-post-deployment-tests.yaml
.gitignore
tests/smoke-tests/dtos-cohort-manager-smoke-tests/Config/AppSettings.cs
tests/smoke-tests/dtos-cohort-manager-smoke-tests/Config/appsettings.json
tests/smoke-tests/dtos-cohort-manager-smoke-tests/Features/FileUploadAndCohortDistribution.feature
tests/smoke-tests/dtos-cohort-manager-smoke-tests/Helpers/BlobStorageHelper.cs
tests/smoke-tests/dtos-cohort-manager-smoke-tests/Helpers/DatabaseHelper.cs
tests/smoke-tests/dtos-cohort-manager-smoke-tests/Helpers/DatabaseValidationHelper.cs
tests/smoke-tests/dtos-cohort-manager-smoke-tests/README.md
tests/smoke-tests/dtos-cohort-manager-smoke-tests/Startup.cs
tests/smoke-tests/dtos-cohort-manager-smoke-tests/Steps/FileUploadAndCohortDistributionSteps.cs
tests/smoke-tests/dtos-cohort-manager-smoke-tests/TestServices/EndToEndFileUploadService.cs
tests/smoke-tests/dtos-cohort-manager-smoke-tests/dtos-cohort-manager-smoke-tests.csproj

- Introduction of YAML files to run smoke tests
- Added Reamme file
- Refactored code to take managed identity parameter
So we can run smoke tests in Azure pipeline
- [x ] Refactoring (non-breaking change)
- [ x] New feature (non-breaking change which adds functionality)
- [x ] I have added tests to cover my changes
- [x ] I have updated the documentation accordingly
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other …

feat: DTOSS-7253-Pipeline code to run  automation tests

---

.azuredevops/pipelines/cd-infrastructure-dev-audit.yaml
.azuredevops/pipelines/cd-infrastructure-dev-core.yaml
.azuredevops/pipelines/cd-infrastructure-int-audit.yaml
.azuredevops/pipelines/cd-infrastructure-int-core.yaml
.azuredevops/pipelines/cd-infrastructure-nft-audit.yaml
.azuredevops/pipelines/cd-infrastructure-nft-core.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-audit.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-core.yaml

-Updating all pipelines to point at the latest Template repo commit. 
---

feat: DTOS 7243 updated Template commit ref for pipeline

---

docs/user-guides/Local_machine_setup.md

- Changed the docs to use 1Passwords instructions for signing git commits
1Password's setup is much easier and does not require a password every time you commit something. It is available to all IBMers
---

feat: update docs on commit signing to recommend using 1Password

---

application/CohortManager/compose.cohort-distribution.yaml
application/CohortManager/compose.core.yaml
application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataLookupFacade.cs
application/CohortManager/src/Functions/Shared/Model/CohortDistributionParticipant.cs

- Some dates were appearing as null in the cohort distribution table due to incorrect parsing
[DTOSS-7383](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7383)
---

fix: date parsing

---

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/namePrefixRules.json

fix: MAJ name prefix misspelled in rules

---

application/CohortManager/src/Functions/CohortDistributionServices/ValidateCohortDistributionRecord/ValidateCohortDistributionRecord.cs
application/CohortManager/src/Functions/CohortDistributionServices/ValidateCohortDistributionRecord/host.json
application/CohortManager/src/Functions/Shared/Common/CallFunction.cs
application/CohortManager/src/Functions/screeningDataServices/createParticipant/host.json
application/CohortManager/src/Functions/screeningDataServices/markParticipantAsEligible/host.json

fix: extend function timeouts

---

application/CohortManager/src/Functions/Shared/DataServices.Core/DataServiceAccessor.cs
application/CohortManager/src/Functions/Shared/DataServices.Core/Extensions/DataServicesCoreExtension.cs

fix: data service performance changes

---

application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/host.json
application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/host.json
application/CohortManager/src/Functions/ParticipantManagementServices/updateParticipant/host.json

feat: change queue polling intervals

---

application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
application/CohortManager/src/Functions/Shared/Common/ExceptionHandler.cs
application/CohortManager/src/Functions/screeningDataServices/markParticipantAsEligible/markParticipantAsEligible.cs

making sure that exceptons are working in the system
---

fix: making sure that exceptons are working in the system

---

application/CohortManager/src/Functions/CohortDistributionServices/ValidateCohortDistributionRecord/host.json
application/CohortManager/src/Functions/screeningDataServices/createParticipant/host.json
application/CohortManager/src/Functions/screeningDataServices/markParticipantAsEligible/host.json

feat: increase function timeouts

---

application/CohortManager/compose.cohort-distribution.yaml

fix: wrong port in compose.yaml

---

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/Program.cs
application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Program.cs
application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceCacheClient.cs
application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceClientBuilder.cs
application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceStaticCachedClient.cs

feat: pre caching all lookupdata

---

application/CohortManager/src/Functions/Shared/Common/CallFunction.cs

fix: extend get request timeout

---

infrastructure/tf-core/environments/development.tfvars

In order to better manage the load on the App Service Plan(s) induced by the function apps, split several high-load functions into a dedicated plan.
This is to allow high data loads to be processed without timeouts.
---

fix: DTOSS-7548 Add App Service Plan for High Load Functions (Dev)

---

application/CohortManager/src/Functions/Shared/DataServices.Core/DataServiceAccessor.cs

fix: ensure all db is done with awaits.

---

infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars

NFT and INT refresh config for adding new function apps
---

feat: dtoss 6687 nft and int refresh config for adding new function apps

---

infrastructure/tf-core/function_app.tf

fix: Update database connection string

---

infrastructure/tf-core/environments/nft.tfvars

fix: New App Service Plan for NFT plus SQL config

---

application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs

feat: add logging for debugging

---

infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/function_app.tf
infrastructure/tf-core/variables.tf

Testing connectivity issues.
---

fix: don't pull images over VNet for NFT

---

application/CohortManager/src/Functions/CohortDistributionServices/ValidateCohortDistributionRecord/ValidateCohortDistributionRecord.cs

…e returned list
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7613
---

fix: now using get by filter and then getting last or default from the returned list

---

infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars

Added a missing `AcceptableLatencyThresholdMs` static environmental variable for `screening-lkp-data-service` function in NFT and Integration environments.
Variable has been created manually in the Portal, so it already exists.
---

chore: missing env var for NFT and Integration tfvars

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/HealthCheckFunction.cs
application/CohortManager/src/Functions/screeningDataServices/ScreeningLkpDataService/HealthCheckFunction.cs

feat: DTOSS-0000 Health check 401 issue fix

---

infrastructure/tf-core/environments/preprod.tfvars

Merge latest function app changes, including data service functions and durable functions, into Pre Prod config.
---

fix: DTOSS-7699 Update PreProd with latest

---

application/CohortManager/src/Functions/Shared/Common/EnumHelper.cs

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7700
---

fix: Method now handles null or an empty string without erroring

---

application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/Program.cs
application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/HealthCheckFunction.cs
application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/Program.cs
application/CohortManager/src/Functions/CohortDistributionServices/AddCohortDistributionData/AddCohortDistributionData.csproj
application/CohortManager/src/Functions/CohortDistributionServices/AddCohortDistributionData/HealthCheckFunction.cs
application/CohortManager/src/Functions/CohortDistributionServices/AddCohortDistributionData/Program.cs
application/CohortManager/src/Functions/Shared/HealthChecks/BasicHealthCheck.cs
application/CohortManager/src/Functions/Shared/HealthChecks/Extensions/BasicHealthCheckExtension.cs
application/CohortManager/src/Functions/Shared/HealthChecks/Extensions/BlobStorageHealthCheckExtension.cs
application/CohortManager/src/Functions/Shared/HealthChecks/Extensions/DatabaseHealthCheckExtension.cs
application/CohortManager/src/Functions/screeningDataServices/ScreeningLkpDataService/Program.cs

We need to... Add code for a health check in AddCohortDistributionData to enable the automated end to end tests.
[DTOSS-7669](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7669)
---

feat: DTOS-7669 healthcheck AddCohortDistributionData and code refactor

---

application/CohortManager/src/Functions/screeningDataServices/ParticipantManagementDataService/HealthCheckFunction.cs
application/CohortManager/src/Functions/screeningDataServices/ParticipantManagementDataService/ParticipantManagement.csproj
application/CohortManager/src/Functions/screeningDataServices/ParticipantManagementDataService/Program.cs

We need to... Add code for a health check in ParticipantManagementDataService to enable the automated end to end tests.
[DTOSS-7710](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7710)
---

feat: DTOSS-7710 HealthCheck ParticipantManagementDataService

---

application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformString.cs
tests/UnitTests/CohortDistributionTests/CreateCohortDistributionTests/CreateCohortDistributionTests.cs

- Changed error handling for exceptional characters so it returns a 202 instead of 500
- Removed duplicate exception logging for transform exceptions in create-cohort-distribution and transform-data-service
[DTOSS-7525](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7525)
---

feat: change transform error handling

---

infrastructure/tf-core/environments/preprod.tfvars

Pre Prod config changes for Parallel Run.
---

fix: dtoss-7765 Parallel run config

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs

chore: removing a line from ReceiveCaasFilet to test pipeline changes

---

application/CohortManager/src/Functions/screeningDataServices/markParticipantAsEligible/markParticipantAsEligible.cs
tests/UnitTests/ScreeningDataServicesTests/MarkParticipantAsEligibleTests/MarkParticipantAsEligibleTests.cs

Increases test coverage for markParticipantAsEligible to 100%.
---

test: increase unit test coverage for markParticipantAsEligible

---

tests/UnitTests/DataServiceTests/BsSelectGpPracticeDataServiceTests.cs

Increases unit test coverage to 100% for BsSelectGpPracticeDataService.
[DTOSS-7869](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7869)
---

test: increase unit test coverage for BsSelectGpPracticeDataService

---

tests/UnitTests/DataServiceTests/BsSelectOutCodeDataServiceTests.cs

Increases unit test coverage to 100% for BsSelectOutCodeDataService.
[DTOSS-7870](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7870)
---

test: increase unit test coverage for BsSelectOutCodeDataService

---

tests/UnitTests/DataServiceTests/CurrentPostingDataServiceTests.cs

Increase unit test coverage to 100% for CurrentPostingDataService.
Also quite a lot of formatting changes to this test file.
[DTOSS-7878](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7878)
---

test: increase unit test coverage for CurrentPostingDataService

---

application/CohortManager/src/Functions/Functions.sln
tests/UnitTests/SharedTests/ReadRulesTests/ReadRulesTests.cs
tests/UnitTests/SharedTests/ReadRulesTests/ReadRulesTests.csproj

Adds unit tests which add 80% coverage to ReadRules.cs.
[DTOSS-7737](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7737)
---

test: add unit tests for ReadRules

---

application/CohortManager/src/Functions/screeningDataServices/CohortDistributionDataService/CohortDistributionDataService.cs
tests/UnitTests/DataServiceTests/CohortDistributionDataServiceTests.cs
tests/UnitTests/DataServiceTests/DataServiceTests.csproj

Adds 100% unit test coverage to CohortDistributionDataService.
[DTOSS-7874](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7874)
---

test: add unit test coverage for CohortDistributionDataService

---

tests/UnitTests/DataServiceTests/DataServiceTests.csproj
tests/UnitTests/DataServiceTests/ExceptionManagementDataServiceTests.cs

Adds 100% unit test coverage for ExceptionManagementDataService.
[DTOSS-7885](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7885)
---

test: add unit test coverage for ExceptionManagementDataService

---

tests/UnitTests/DurableDemographicTests/DurableDemographicTests.cs
tests/UnitTests/DurableDemographicTests/DurableDemographicTests.csproj

- Added a test to make sure the function errors when the activity times out
---

test: add timeout test to durable demographic

---

application/CohortManager/src/Functions/screeningDataServices/markParticipantAsIneligible/markParticipantAsIneligible.cs
application/CohortManager/src/Functions/screeningDataServices/markParticipantAsIneligible/markParticipantAsIneligible.csproj
tests/UnitTests/ScreeningDataServicesTests/MarkParticipantAsIneligibleTests/MarkParticipantAsIneligibleTests.cs

Increase unit test coverage for markParticipantAsIneligible to 90%
[DTOSS-7945](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7945)
---

test: increase markParticipantAsIneligible unit test coverage

---

.gitignore
application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/Program.cs
application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFile.csproj
application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFileConfig.cs
tests/UnitTests/StaticTests/ValidationHelperTests.cs

- New solution for e2e tests
- Total 4 scenarios fully tested
- [x ] Refactoring (non-breaking change)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have added tests to cover my changes
- [ x] I have updated the documentation accordingly
- [x ] This PR is a result of pair or mob programming
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the …

feat: epic1 high priority tests

---

tests/UnitTests/StaticTests/ValidationHelperTests.cs

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7738
---

chore: Added more tests and removed a test case for an unused method

---

application/CohortManager/src/Functions/CohortDistributionServices/AddCohortDistributionData/AddCohortDistributionData.cs
application/CohortManager/src/Functions/Functions.sln
tests/UnitTests/CohortDistributionTests/AddCohortDistributionDataTests/AddCohortDistributionDataTests.cs
tests/UnitTests/CohortDistributionTests/AddCohortDistributionDataTests/AddCohortDistributionDataTests.csproj

Adds 100% unit test coverage for AddCohortDistributionData.
[DTOSS-7957](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7957)
---

test: AddCohortDistributionData unit test coverage

---

application/CohortManager/src/Functions/ParticipantManagementServices/RemoveParticipant/Program.cs
application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/Program.cs
application/CohortManager/src/Functions/ParticipantManagementServices/updateParticipant/Program.cs
application/CohortManager/src/Functions/Shared/Common/Extensions/AzureQueueExtension.cs
tests/smoke-tests/dtos-cohort-manager-smoke-tests/Config/appsettings-local.json

injecting queue factory into the AzureQueueExtension
---

fix: making sure queue factory is injected

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars

[DTOSS-7958](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7958)
[DTOSS-7959](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7959)
---

feat: enabling healthcheck config and scaling down DBs to S1 SKU

---

application/CohortManager/src/Functions/Shared/rebuild.all

A manual docker rebuild process.
Previously images building stage didn't run due to failed unit tests.
---

chore: rebuild all docker images

---

application/CohortManager/src/Functions/Shared/Common/ValidationHelper.cs

Validation errors are occurring when the effective_date_from was equal to the current date. 
---

fix: Allow for today's date to stop validation errors

---

.vscode/tasks.json
docs/user-guides/Local_machine_setup.md

accidentally left the option to use wsl as the shell for the mac tasks
---

fix: tasks.json

---

infrastructure/tf-core/environments/nft.tfvars

An update to the nft.tfvars file prior to environment refresh. 
Changes include:
- healthcheck configuration for function apps
- new function app resource (ReceiveServiceNowMessage)
A successful plan using this branch below:
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=16746&view=logs&j=ced2749f-787a-529b-d064-72b5c61df22f&t=a8ef944f-7917-542a-f805-14b39eb0c11c
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any …

chore: NFT tfvars file update

---

infrastructure/tf-core/environments/integration.tfvars

Updating the Azure infrastructure prior to refreshing the Integration CohMan environment.
Implemented:
- healthchecks for function apps
- new function app resource (ReceiveServiceNowMessage)
---

chore: refresh the Integration environment

---

.azuredevops/pipelines/acr-image-promote-dev-to-nft.yaml
.azuredevops/pipelines/acr-image-promote-nft-to-integration.yaml
.azuredevops/pipelines/acr-image-promote-to-dev.yaml

Add Database Migration (aka Database Management) step to Dev, NFT and INT image pipelines for evaluation in daily use.
Note, the database migration itself will not be performed at present as deploying the container instance is commented out in the back-end template file, but the changes proposed in this PR will allow us to validate the rest of the end to end process.
The managed identities required by the container instance to authenticate to SQL Server have been created and added as SQL Database Users via T-SQL script.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-pu …

feat: dtoss-3550: Database management pipeline updates (Dev)

---

application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs

did not await on the log audit request meaning in azure it was not adding the request to the audit table
---

fix: now awaits logging audit request

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars

…nction
A fix with a correct endpoint name for the BsSelectRequestAuditDataService function.
Previously:
`BsRequestAuditDataService`
Corrected one:
`BsSelectRequestAuditDataService`
---

fix: correct endpoint name for the BsSelectRequestAuditDataService function

---

application/CohortManager/compose.core.yaml
application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/CertificateHelper.cs
application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/Program.cs
application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFileConfig.cs
infrastructure/tf-core/environments/development.tfvars

- MESH certs were updated which required some changes so that the cert can be read from an azure keyvault secret
[DTOSS-8368](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8368)
---

feat: update mesh cert handling

---

infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars

New static environment variable for Mesh Mailbox certificate changes
---

feat: Add MeshCertName environment variable

---

.azuredevops/pipelines/post-deployment-tests-dev.yaml
tests/playwright-tests/src/config/playwright.config.ts

test: dtoss 8459 junit reporting

---

.azuredevops/pipelines/acr-image-promote-to-devtest.yaml
.azuredevops/pipelines/cd-infrastructure-devtest-audit.yaml
.azuredevops/pipelines/cd-infrastructure-devtest-core.yaml
infrastructure/tf-audit/environments/devtest.tfvars
infrastructure/tf-core/environments/devtest.tfvars

To allow Cohort Manager infra changes to be tried and tested before deploying to the Non-Live and Live environments, a DevTest environment is required in the Sandbox subscription, accessible by the platform team.
This change will allow Terraform and other Infra changes to be deployed prior to rolling out in the Dev, NFT etc environments that are in continual use by the Dev and QA teams.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any …

feat: Build DevTest sandbox environment

---

infrastructure/tf-core/environments/preprod.tfvars

The RemoveValidationException function is not executing correctly in one (or more) ASP instances despite rebuilding the function app. It is possible that resource limits in the DefaultPlan ASP resource are a contributing factor, so the function will be moved to its own ASP.
---

fix: Function App ASP service issue fix

---

.azuredevops/pipelines/acr-image-promote-dev-to-nft.yaml
.azuredevops/pipelines/acr-image-promote-nft-to-integration.yaml
.azuredevops/pipelines/acr-image-promote-to-dev.yaml
.azuredevops/pipelines/acr-image-promote-to-devtest.yaml
tests/playwright-tests/package.json
tests/playwright-tests/src/api/apiHelper.ts
tests/playwright-tests/src/tests/e2e/e2e-with-db.spec.ts

**We need to...**
update below calls
dtos-cohort-manager/.azuredevops/pipelines/acr-image-promote-to-dev.yaml at main · NHSDigital/dtos-cohort-manager
dtos-cohort-manager/.azuredevops/pipelines/acr-image-promote-dev-to-nft.yaml at main · NHSDigital/dtos-cohort-manager
dtos-cohort-manager/.azuredevops/pipelines/acr-image-promote-nft-to-integration.yaml at main · NHSDigital/dtos-cohort-manager
**In order for...**
running the latest playwright smoke pack on cloud when these environments are refreshed 
**To...**
make sure regression smoke functionality does not break on new deployments
**Acceptance Criteria:**
All existing 5 smoke tests should pass on cloud
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal …

test: dtoss 8557 integrate pw tests stages

---

tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-7960-01/ADD_Exception_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8612
---

test: fix add back test data for verify GP Practice Code Exception flag in participant management set to 1

---

tests/playwright-tests/src/tests/fixtures/test-fixtures.ts

Alter the code to cater request better in fixtures class
so it is more easily readable
- [x ] Refactoring (non-breaking change)
- [x ] I have added tests to cover my changes
- [ x] I have updated the documentation accordingly
- [x ] This PR is a result of pair or mob programming
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR …

fix: declared the request better in fixtures

---

.gitignore

issue with gitignore was preventing files from being added to the repo
issue with gitignore was preventing files from being added to the repo
---

fix: git ignore issue

---

application/CohortManager/src/Functions/Functions.sln

sln file had a wrong path defined.
sln was reporting errors as a project couldnt be loaded
---

fix: sln wrong project path

---

application/CohortManager/src/Functions/Functions.sln

The NemsSubscriptionDataService project in the sln file is missing a quote mark, which is preventing building the solution.
---

fix: add missing quote mark to project in sln file

---

tests/playwright-tests/package.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-3661-01/ADD2_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-3661-02/ADD1_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-3661-02/AMENDED1_-_CAAS_BREAST_SCREENING_COHORT.json

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8736
---

test: fix add back missing test data files

---

tests/playwright-tests/src/tests/steps/steps.ts

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8768
---

test: fix testDataHelper location

---

.azuredevops/pipelines/cd-infrastructure-dev-audit.yaml
.azuredevops/pipelines/cd-infrastructure-devtest-audit.yaml
.azuredevops/pipelines/cd-infrastructure-int-audit.yaml
.azuredevops/pipelines/cd-infrastructure-nft-audit.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-audit.yaml
.azuredevops/pipelines/cd-infrastructure-sandbox-audit.yaml
infrastructure/tf-audit/environments/sandbox.tfvars
infrastructure/tf-audit/outputs.tf
infrastructure/tf-audit/providers.tf

Decomposition of PR described here in order to deploy changes in just Audit environments as a pre-cursor to applying the full changes in Core environments:
https://github.com/NHSDigital/dtos-cohort-manager/pull/907
Tech debt remediation
---

feat: Update TF provider version in Audit environments

---

application/CohortManager/src/Functions/Shared/Model/Participant.cs

Fixed a bug where the exception flag field was being read in as the blocked flag field
---

fix: Bug where exception flag was being called instead of blocked flag

---

application/CohortManager/src/Functions/Shared/rebuild.all

Just a small change to trigger the CI image rebuild process.
The CI is failing and we want to make sure it's a code change, not the process itself.
---

chore: rebuilding all images to verify the CI

---

application/CohortManager/src/Functions/Shared/rebuild.all

Automatically rebuild all images after merging CI changes.
---

chore: CI testing 1 - rebuild all

---

tests/playwright-tests/package.json
tests/playwright-tests/src/tests/e2e/epic3-highpriority-tests/epic3-high-priority-testsuite.spec.ts
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-5584-01/ADD1_-_CAAS_BREAST_SCREENING_COHORT.json

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8982
---

test: check bs select 204 when IsExtracted is true

---

.github/workflows/cicd-4-manual-rebuild.yaml

A corrected approach to the manual image rebuild process. 
The `workflow_dispatch` method needs to be implemented not within the templates repository, but within the project repository. A new workflow `cicd-4-manual-rebuild.yaml` has been introduced, which needs to be created in other projects as well.
For now, this workflow is using the `stage-3-build-images.yaml` from a templates repo feature branch. 
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do …

feat: DTOSS-8936 manual image rebuild workflow 

---

tests/UnitTests/ParticipantManagementServicesTests/UpdateParticipantTests/UpdateParticipantTests.cs

fixes a broken test due to a recent PR changing a method's signature
---

fix: UpdateParticipantTests

---

.azuredevops/pipelines/cd-infrastructure-dev-audit.yaml
.azuredevops/pipelines/cd-infrastructure-dev-core.yaml
.azuredevops/pipelines/cd-infrastructure-int-audit.yaml
.azuredevops/pipelines/cd-infrastructure-int-core.yaml
.azuredevops/pipelines/cd-infrastructure-nft-audit.yaml
.azuredevops/pipelines/cd-infrastructure-nft-core.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-audit.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-core.yaml
.azuredevops/pipelines/cd-infrastructure-sandbox-audit.yaml
.azuredevops/pipelines/cd-infrastructure-sandbox-core.yaml
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/sandbox.tfvars

Terraform templates have been updated and pipeline yaml templates need updating to reflect this.
Also taking the opportunity to tidy up two bits of incorrect config in Pre PRod environment:
* Linux Web App Slots are not required for the time being
* BypassServerCertificateValidation Env Var is required while parallel run is ongoing.
Evidence of unchanged plan as a result:
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=18286&view=logs&j=ced2749f-787a-529b-d064-72b5c61df22f&t=a8ef944f-7917-542a-f805-14b39eb0c11c
Brings templates up to date.
--- …

fix: Update template version to latest

---

scripts/reports/sonar-analysis.sh

At the moment coverage reporting is working for PRs, but not on the main branch in SonarCloud - main is always showing at 0% which we know isn't right.
Added the scanAll property to the sonar scanner to see if it helps
Made sure the branch name is sent to sonar when running against main to reduce variables
added additional logging to the pipeline to see if coverage reports are definitely being uploaded when running against main.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We …

feat: DTOSS-7817 sonar cloud coverage - attempt to fix coverage reporting for main branch

---

application/CohortManager/src/Functions/Shared/Common/ValidationHelper.cs

attempting to fix issue: https://sonarcloud.io/project/security_hotspots?id=NHSDigital_dtos-cohort-manager&sinceLeakPeriod=true
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9088
---

fix: adding time to regax match in ValidatePostcode

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/sandbox.tfvars

Follow-on PR from #995 to add Terraform config required to run the new function.
Adds new Exception Management functionality.
---

feat: Add UpdateException to Terraform config

---

tests/UnitTests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs

…aths
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9121
added an extra possible path to the lists of possible paths
---

fix: the rules file path was not  in the list of possible paths list

---

application/CohortManager/compose.core.yaml

fix: compose config

---

application/CohortManager/Set-up/database/Dockerfile

Fixing the following Security Hotspots in Sonarqube:
https://sonarcloud.io/project/security_hotspots?id=NHSDigital_dtos-cohort-manager&hotspots=AZVmJ_ONedHgGhLiTLmo 
---

feat: DTOSS-0000 fix sonarqube issue

---

.github/workflows/cicd-4-manual-rebuild.yaml

A new version of the manual trigger workflow
---

fix: DTOSS-8936 - new version of the manual trigger workflow

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_cohortRules.json
application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/DataLookupFacadeBreastScreening.cs
tests/UnitTests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs

fix for rule 54 logic being wrong according to the original ticket [DTOSS-4283](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-4283)
[DTOSS-9100](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9100)
---

fix: rule 54

---

.azuredevops/pipelines/acr-image-promote-dev-to-nft.yaml
.azuredevops/pipelines/acr-image-promote-nft-to-integration.yaml
.azuredevops/pipelines/acr-image-promote-to-dev.yaml
.azuredevops/pipelines/acr-image-promote-to-sandbox.yaml
.azuredevops/pipelines/post-deployment-tests-dev.yaml

New Slack Integrations have been added to the automation Tests pipeline templates. These need to be called in the Cohort Manager Post-Deployment Tests and Image Management pipelines to send the success/failure notification after the tests run.
Improves visibility of test results.
---

feat: dtoss Integrate post deployment tests with slack

---

tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-6406-01/ADD_Exception_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9206
A fix to Rule 36 test
---

test: Fix rule 36 test

---

.github/workflows/cicd-4-manual-rebuild.yaml

A new workflow to trigger the manual rebuild process.
---

fix: DTOSS-8936 manual image rebuild refinement

---

tests/playwright-tests/src/tests/e2e/epic2-highpriority-tests/epic2-high-priority-testsuite.spec.ts
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-5418-01/ADD1_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-5418-01/AMENDED1_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9323
Epic2 high level tests
---

test: Full test for epic2 high level tests

---

application/CohortManager/compose.core.yaml

Dockerfile had capital F which is wrong
---

fix: dockerfile name

---

tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-5406-01/ADD1_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9399
---

test: fix add test data nhs participant number for scenario 5406-01

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars

fix: add missing env var to create cohort distribution

---

application/CohortManager/compose.core.yaml

fix: docker path

---

application/CohortManager/compose.core.yaml
application/CohortManager/src/Functions/ServiceNowIntegrationService/ReceiveServiceNowMessage/Dockerfile
application/CohortManager/src/Functions/ServiceNowIntegrationService/SendServiceNowMessage/Dockerfile

fix: dockerfiles

---

application/CohortManager/src/Functions/screeningDataServices/GetValidationExceptions/Program.cs

fix for GetValidationExceptions API.
AddHttpClient() service added to program.cs as fix.
---

fix: DTOSS-0000 fix for GetValidationExceptions

---

application/CohortManager/src/Functions/NemsSubscriptionService/ProcessNemsUpdate/ProcessNemsUpdate.csproj

fix: updating function worker runtime in nems

---

tests/playwright-tests/package.json
tests/playwright-tests/src/api/apiHelper.ts
tests/playwright-tests/src/tests/e2e/epic3-highpriority-tests/epic3-high-priority-testsuite.spec.ts
tests/playwright-tests/src/tests/steps/steps.ts

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9633
---

test: fix test script for checking latest record in bs select audit api

---

infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/sandbox.tfvars

Fix Database Management image names and tag in non-dev environments
---

fix: Fix Database Management image names and tag in non-dev environments

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFileConfig.cs
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/function_app.tf

…tion worker runtime to dotnet isolated in RCF
---

fix: adding missing App urls and static vars to RCF 

---

application/CohortManager/src/Web/app/accessibility-statement/page.tsx
application/CohortManager/src/Web/app/components/footer.tsx
application/CohortManager/src/Web/app/contact-us/page.tsx
application/CohortManager/src/Web/app/cookies-policy/page.tsx
application/CohortManager/src/Web/app/globals.scss
application/CohortManager/src/Web/app/terms-and-conditions/page.tsx

[DTOSS-6329](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6329) - Add the legal pages for accessibility statement, cookies policy and terms and conditions
[DTOSS-9551](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9551) - Add the contact us page
---

feat: add legal pages and the contact us page

---

application/CohortManager/compose.core.yaml

fix: docker compose

---

tests/playwright-tests/src/api/apiHelper.ts
tests/playwright-tests/src/tests/e2e/epic3-medpriority-tests/epic3-med-priority-testsuite.ts
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-6325-01/ADD_CAAS_BREAST_SCREENING_COHORT.json

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9738
---

test: exception validation no transformation for invalid flag true pcp null add

---

application/CohortManager/src/Functions/Shared/Data/Database/IValidationExceptionData.cs
application/CohortManager/src/Functions/Shared/Data/Database/ValidationExceptionData.cs
application/CohortManager/src/Functions/Shared/Model/EFModels/ExceptionManagement.cs
application/CohortManager/src/Functions/Shared/Model/ValidationException.cs
application/CohortManager/src/Functions/screeningDataServices/GetValidationExceptions/GetValidationExceptions.cs
tests/UnitTests/ScreeningDataServicesTests/ValidationExceptionDataTests/GetValidationExceptionTests/GetValidationExceptionsTests.cs
tests/UnitTests/ScreeningDataServicesTests/ValidationExceptionDataTests/ValidationExceptionDataTests/ValidationExceptionDataTests.cs

Removed Today Only functionality 
Added Null handling around exceptions list 
Updated Tests 
Exceptionid is no longer nullable 
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9609
---

feat: Validation Exception Remove TodayOnly

---

.azuredevops/pipelines/post-deployment-tests-dev.yaml

Added automated regression test jobs as stages for better control
Added scheduler for running automated test jobs in the morning on weekday.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9654
- [Y] New feature (non-breaking change which adds functionality)
- [Y] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [Y] I have followed the code style of the project
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any …

feat: dtoss 9654 run full regression and schedule

---

tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-4089-01/ADD1_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-4219-01/ADD1_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-4219-01/AMENDED1_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-4322-01/AMENDED6_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-4356-01/ADD1_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-4371-01/ADD3_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-5605-01/ADD1_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-5605-01/AMENDED1_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9773
---

test: fix epic2 high test script issues

---

tests/playwright-tests/src/tests/e2e/epic3-medpriority-tests/epic3-med-priority-testsuite.ts
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-5579-01/ADD_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-5579-01/AMENDED_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9801
---

test: check cohort is not updated when exception on amend

---

application/CohortManager/src/Functions/CohortDistributionServices/DistributeParticipant/DistributeParticipant.csproj
application/CohortManager/src/Functions/ParticipantManagementServices/ManageParticipant/ManageParticipant.csproj
application/CohortManager/src/Functions/Shared/Common/AzureServiceBusClient.cs
application/CohortManager/src/Functions/Shared/Common/Common.csproj
application/CohortManager/src/Functions/Shared/Common/Extensions/AzureQueueExtension.cs
application/CohortManager/src/Functions/Shared/Common/Extensions/ExceptionHandlerServiceExtension.cs
application/CohortManager/src/Functions/Shared/Common/SendExceptionToServicBus.cs
application/CohortManager/src/Functions/Shared/DataServices.Migrations/DataServices.Migrations.csproj

- Upgrade some nuget packages due to incompatibility (Azure Identity and servicebus extension)
- Refactor AzureServiceBusClient to use DI and Azure Clients to manage creation of sender class and Auth
- Add AzureQueue Keyed Client to allow for multiple different clients to be implemented in one function (Storage Queues and Service Bis)
- Adding Authentication to ServiceBus Client
- Allowing Storage queues and Service Bus to be used in parallel
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase …

feat: Azure ServiceBus Client Auth and Keyed Services

---

tests/playwright-tests/src/tests/e2e/epic3-medpriority-tests/epic3-med-priority-testsuite.ts
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-5582-01/ADD_CAAS_BREAST_SCREENING_COHORT.json

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9825
---

test: is extracted set to false for new add participant

---

.azuredevops/pipelines/acr-image-promote-dev-to-nft.yaml
.azuredevops/pipelines/acr-image-promote-nft-to-integration.yaml
.azuredevops/pipelines/acr-image-promote-to-dev.yaml
.azuredevops/pipelines/acr-image-promote-to-sandbox.yaml
.azuredevops/pipelines/post-deployment-tests-dev.yaml

Added config to pipeline to run full regression automation pack in higher cloud environments 
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9815
---

feat: DTOSS-9815 full regression nft dev

---

tests/playwright-tests/src/api/core/requestClient.ts
tests/playwright-tests/src/tests/e2e/epic3-highpriority-tests/epic3-high-priority-testsuite.spec.ts
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-5561-01/ADD_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/fixtures/test-fixtures.ts
tests/playwright-tests/src/tests/fixtures/testDataHelper.ts
tests/playwright-tests/src/tests/steps/steps.ts

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9880
---

test: check IsExtracted set to 1 n RequetId set to uuidv4 format when Bs Select Retrieve Cohort API is called

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/service_bus_subscriptions.tf

Minor changes to new Service Bus deployment to accommodate latest code updates, mainly changing the name of topic subscriptions from <topic-name>-<Subscriber> to simple <Subscriber>.
---

feat: DTOSS-9800 service bus ongoing rollout

---

.azuredevops/pipelines/acr-image-promote-nft-to-integration.yaml
.azuredevops/pipelines/acr-image-promote-to-sandbox.yaml

One of earlier PR resulted in failures of INT pipeline. This PR is to fix padding issue in yml for promoting code from NFT to INT
This PR is to fix padding issue in yml for promoting code from NFT to INT
---

test: fix padding issue

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/sandbox.tfvars

Further minor fixes to synchronise Service Bus environment variable names across app code and Azure environments.
---

fix: dtoss-9810 Service Bus environment name changes continued..

---

application/CohortManager/compose.cohort-distribution.yaml
application/CohortManager/compose.core.yaml
application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/Program.cs
application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFileConfig.cs
application/CohortManager/src/Functions/CohortDistributionServices/DistributeParticipant/Program.cs
application/CohortManager/src/Functions/Shared/Common/Extensions/AzureQueueExtension.cs

- changed the queue extension to use the AddServiceBusClientWithNamespace if the connection string is a namespace
- removed the AddAzureQueues call from distribute participant because it doesn't send anything to queues
- updated env var names to match tf
---

fix: service bus managed identities

---

application/CohortManager/src/Web/app/components/authError.tsx

remove the unused useSearchParams
---

fix: remove the unused useSearchParams

---

.github/workflows/cicd-1-pull-request.yaml
.github/workflows/cicd-4-manual-test.yaml

First version of the manual testing stage workflow. It will probably get deleted after the Snapshot Integration is finished.
Initial version, but need to be in main so I can trigger it. 
---

feat: manual workflow to trigger testing stage

---

.github/workflows/stage-2-test.yaml

A fix for a missing app_dir variable in `stage-2-test.yaml`.
---

fix: defined the missing app_dir input in stage-2-test workflow

---

.azuredevops/pipelines/acr-image-promote-dev-to-nft.yaml
.azuredevops/pipelines/acr-image-promote-nft-to-integration.yaml
.azuredevops/pipelines/acr-image-promote-to-dev.yaml
.azuredevops/pipelines/acr-image-promote-to-sandbox.yaml

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9995
---

test: fix npm test command in cd pl for all environments

---

infrastructure/tf-core/container_app_job.tf
infrastructure/tf-core/data.tf
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/production.tfvars
infrastructure/tf-core/environments/sandbox.tfvars
infrastructure/tf-core/locals.tf
infrastructure/tf-core/sql_server.tf
infrastructure/tf-core/variables.tf

The Database Management container app job that updates the database during a deployment was initially deployed with a manually built managed identity.
This PR switches to using a managed identity created in the SQL Server module to reduce external dependencies.
Once the new MI has been created for a given environment, it should be added (via the portal) to the relevant sqlsvr_cohman_xxx_uks_admin Entra group to provide it with the required database permissions.
Then, the old identity should be:
a) Removed as a database login
b) Deleted from Entra
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data- …

feat: DTOSS-10175: Add Creation of DB Management Managed Identity to Terraform

---

infrastructure/tf-core/environments/development.tfvars

fix: add back in retrieve cohort distribution

---

tests/playwright-tests/package.json
tests/playwright-tests/src/tests/api/snow/receiveData/receive-participant-snow-function.spec.ts
tests/playwright-tests/src/tests/api/testFiles/@DTOSS-3880-01/ADD-participantPayload.json

- [ x] Refactoring (non-breaking change)
- [x ] I have added tests to cover my changes
---
- [x ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

test: update dtoss 3880 to include dtoss 8424 snow integration

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_lookupRules.json

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9873
---

fix: Update Rule 45

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/production.tfvars
infrastructure/tf-core/environments/sandbox.tfvars

fix: add missing env var

---

tests/playwright-tests/src/api/apiHelper.ts
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-5579-01/AMENDED_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-6325-01/ADD_CAAS_BREAST_SCREENING_COHORT.json

test: fixed_regression_test_failures

---

application/CohortManager/src/Functions/ParticipantManagementServices/ManageServiceNowParticipant/ManageServiceNowParticipantFunction.cs
tests/TestUtils/LoggerAssertions.cs
tests/UnitTests/ParticipantManagementServicesTests/ManageServiceNowParticipantTests/ManageServiceNowParticipantFunctionTests.cs
tests/UnitTests/ScreeningDataServicesTests/ValidationExceptionDataTests/GetValidationExceptionTests/UpdateExceptionServiceNowIdTests.cs

feat: VHR flag added, tests updated, log assertion namespace now file scoped and named correctly, references updated
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9706
---

feat: VHR flag added, tests updated, log assertion namespace now file scoped and named correctly, references updated

---

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformReasonForRemoval.cs
tests/UnitTests/TransformDataServiceTests/TransformReasonForRemovalTests/TransformReasonForRemovalTests.cs

- updated the RFR rule 3 to transform some fields
[DTOSS-10118](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10118)
---

feat: update RFR rule 3

---

application/CohortManager/src/Web/app/participant-information/[exceptionId]/page.tsx
application/CohortManager/src/Web/tests/features/pages/exceptionInformationPage.ts
application/CohortManager/src/Web/tests/features/pages/exceptionOverviewPage.ts
application/CohortManager/src/Web/tests/features/raisedExceptionInformation.feature
application/CohortManager/src/Web/tests/features/steps/exceptionInformationSteps.ts

- [ x] Refactoring (non-breaking change)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
---
- [ x] I confirm that neither PII/PID nor sensitive data are included in this …

test: added tests for raised exception information screen

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/production.tfvars
infrastructure/tf-core/environments/sandbox.tfvars

Fixed incorrect env var app url endpoint in Terraform
Url endpoint was incorrect so requests were failing
---

fix: Fixed incorrect env var app url endpoint

---

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs

fixes an issue where the referral flag being null causes transformations to fail
temporary, the referral flag should not be null as it is hardcoded so this needs to be investigated further
---

fix: null referral flag issue

---

application/CohortManager/compose.core.yaml
application/CohortManager/src/Functions/NemsSubscriptionService/ProcessNemsUpdate/ProcessNemsUpdate.cs
application/CohortManager/src/Functions/NemsSubscriptionService/ProcessNemsUpdate/ProcessNemsUpdate.csproj
application/CohortManager/src/Functions/NemsSubscriptionService/ProcessNemsUpdate/ProcessNemsUpdateConfig.cs
application/CohortManager/src/Functions/NemsSubscriptionService/ProcessNemsUpdate/Program.cs
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/production.tfvars
infrastructure/tf-core/environments/sandbox.tfvars
tests/UnitTests/NemsSubscriptionServiceTests/ProcessNemsUpdateTests/ProcessNemsUpdateTests.cs
tests/UnitTests/NemsSubscriptionServiceTests/ProcessNemsUpdateTests/ProcessNemsUpdateTests.csproj

Given Cohort Manager receives an AMEND record where the NHS ID has been superseded in PDS
When the superceded NHS ID does not already exist in Cohort Manager i.e. the 'superseded_by_nhs_number' does not match  any 'nhs_number' already in Cohort Manager
Then create a new ADD record in Cohort Manager
[DTOSS-8352](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8352)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really …

feat: DTOSS-8352 pds add record

---

application/CohortManager/src/Web/app/components/dataError.tsx
application/CohortManager/src/Web/app/components/unauthorised.tsx
application/CohortManager/src/Web/app/not-found.tsx

This PR changes the error pages content and links to the new contact us page.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6330
---

feat: content changes for the error pages

---

.github/workflows/ci-ui-tests.yaml
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/production.tfvars
infrastructure/tf-core/environments/sandbox.tfvars

This PR updates the Terraform vars for the new RBAC env variable.
---

fix: update the terraform vars for the new RBAC env var

---

application/CohortManager/compose.cohort-distribution.yaml
application/CohortManager/compose.core.yaml
application/CohortManager/src/Functions/CohortDistributionServices/DistributeParticipant/DistributeParticipant.cs
application/CohortManager/src/Functions/CohortDistributionServices/DistributeParticipant/DistributeParticipantActivities.cs
application/CohortManager/src/Functions/CohortDistributionServices/DistributeParticipant/DistributeParticipantConfig.cs
application/CohortManager/src/Functions/CohortDistributionServices/DistributeParticipant/Program.cs
application/CohortManager/src/Functions/ParticipantManagementServices/ManageServiceNowParticipant/ManageServiceNowParticipantConfig.cs
application/CohortManager/src/Functions/ParticipantManagementServices/ManageServiceNowParticipant/ManageServiceNowParticipantFunction.cs
application/CohortManager/src/Functions/Shared/Model/BasicParticipantCsvRecord.cs
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/production.tfvars
infrastructure/tf-core/environments/sandbox.tfvars
tests/UnitTests/CohortDistributionTests/DistributeParticipantTests/DistirbuteParticipantTests.cs
tests/UnitTests/CohortDistributionTests/DistributeParticipantTests/ValidationTests.cs
tests/UnitTests/ParticipantManagementServicesTests/ManageServiceNowParticipantTests/ManageServiceNowParticipantFunctionTests.cs

- Added a call to DistributeParticipant function
- Added a call to SendServiceNowMessage function to notify ServiceNow of participant being added to cohort
- Marked some config properties as required
[DTOSS-10476](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10476)
---

feat: Added call to DistributeParticipant from ManageServiceNowParticipant function

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars

Add environment variables required for the web frontend. Development, NFT, and Integation environments complete (frontend Key Vault secrets added via Azure Portal). Preprod, Production to follow.
---

feat: DTOSS-10516 frontend webapp config

---

application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/Breast_Screening_staticRules.json
tests/UnitTests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.cs

[DTOSS-10450](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10450)
---

feat: remove rule 47

---

application/CohortManager/src/Web/app/components/participantInformationPanel.tsx
application/CohortManager/src/Web/app/participant-information/[exceptionId]/page.tsx
application/CohortManager/src/Web/app/types/index.d.ts

Display superseded by NHS number if present.
Scenario 2 in https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6328 & https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3913
---

fix: display superseded by NHS number if present

---

tests/PdsProcessorTests/PdsProcessorTests.cs

…ings
this makes sure that all the unit tests are passing
---

fix: some of the unit tests were not updated when we changed the settings

---

infrastructure/tf-core/environments/nft.tfvars

This implements the new ASP instances that have been previously applied in Dev environment: [PR1460](https://github.com/NHSDigital/dtos-cohort-manager/pull/1460/)
Already applied from branch in here:
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=25624&view=results
---

feat: new ASP configuration for NFT environment

---

application/CohortManager/src/Functions/ParticipantManagementServices/ManageServiceNowParticipant/Program.cs

Registered missing service bus client for manage servicenow participant function
Bug fix
---

fix: Registered missing service bus client for manage servicenow participant function

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/production.tfvars

feat: DTOSS-10566 ASP scaling tuning and ASP redeploy for Integration

---

.github/workflows/ci-ui-tests.yaml

fix: remove debug step from the UI test workflow
We don't need this debug step in the workflow
---

fix: remove debug step from the UI test workflow

---

infrastructure/tf-core/environments/development.tfvars

fix: add NODE_ENV to the dev environment to allow stubbed login in the deployed development environment.
To allow for easier testing (without Smartcards) in the development environment.
---

fix: add NODE_ENV to the dev environment to allow stubbed login

---

application/CohortManager/compose.core.yaml

Fixed NEMS subscribe URL in docker compose file
---

chore: Fixed NEMS subscribe URL in docker compose file

---

.github/workflows/cicd-1-pull-request.yaml
.github/workflows/stage-3-build-images.yaml
infrastructure/tf-core/environments/sandbox.tfvars

feat: DTOSS-9902 Test ASP change

---

.github/workflows/cicd-1-pull-request.yaml
.github/workflows/cicd-2-publish.yaml
.github/workflows/stage-3-build-images.yaml

Further minor changes to CI workflows.
---

feat: DTOSS-9902 end to end pipeline GitHub action update

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_lookupRules.json
tests/UnitTests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10089
---

feat: Remove rule 51

---

.github/workflows/cicd-1-pull-request.yaml

Output parameters for debugging
---

feat: DTOSS-9902 Output parameters for debugging

---

.azuredevops/pipelines/adhoc-post-deployment-tests-dev.yaml

Creating a new ADO pipeline for running adhoc tests.
Can run any new tests without changing tags etc
---

feat: adhoc test runner

---

.github/workflows/cicd-1-pull-request.yaml

feat: DTOSS-9902 remove debug condition

---

application/CohortManager/src/Web/app/terms-and-conditions/page.tsx

fix: update terms and conditions
---

fix: update terms and conditions

---

.azuredevops/pipelines/cd-infrastructure-sandbox-core.yaml
.github/workflows/stage-4-deploy.yaml

No longer retag images for Sandbox as only require commit hash to pass to functions now.
---

feat: DTOSS-9902 Amend Workflow config

---

infrastructure/tf-audit/networking.tf
infrastructure/tf-core/networking.tf

Adding extended tags to resource groups.
---

feat: DTOSS-10672 - adding extended tags to resource groups.

---

.azuredevops/pipelines/post-deployment-tests-dev.yaml

Add epic4 tests to Post-Deployment Tests Pipeline:
- regression_e2e_epic4c
- regression_e2e_epic4d      
Increases automated test coverage.
---

test: Add epic4 tests to Post-Deployment Tests Pipeline

---

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformString.cs
application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/characterRules.json

Fixed bugs that were causing failing tests
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10616
---

fix: Medifact Bug 

---

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs
application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/StaticValidation.cs

makes the referral flag check case-insensitive
routine flag was coming in as False with a capital
---

fix: routine rules not running for routine participants

---

application/CohortManager/src/Web/.env.example
application/CohortManager/src/Web/.env.tests
application/CohortManager/src/Web/README.md
application/CohortManager/src/Web/app/components/signIn.tsx
application/CohortManager/src/Web/app/lib/auth.ts
infrastructure/tf-core/environments/development.tfvars

fix: update start page content and remove redundant elements
fix: use `APP_ENV` rather than `NODE_ENV` for Azure web app
Azure automatically sets `NODE_ENV` which cannot be overriden
---

fix: Start page content & use APP_ENV rather than NODE_ENV

---

tests/playwright-tests/src/tests/e2e/epic4d-validation-tests/epic4d-9873-rule45-validation-testsuite.spec.ts

Fixes some issues with the Rule45 tests
---

fix: Update test spec for Rule45

---

tests/playwright-tests/package.json
tests/playwright-tests/src/tests/e2e/epic4b-block-participant-tests/epic-4b-7718-block-paricipant-testsuite.spec.ts

feat: dtoss 7718 end to end tests

---

.azuredevops/pipelines/cd-infrastructure-dev-core.yaml
.azuredevops/pipelines/cd-infrastructure-int-core.yaml
.azuredevops/pipelines/cd-infrastructure-nft-core.yaml
.azuredevops/pipelines/cd-infrastructure-preprod-core.yaml
.azuredevops/pipelines/cd-infrastructure-prod-core.yaml
.azuredevops/pipelines/cd-infrastructure-sandbox-core.yaml
.azuredevops/templates/cd-infrastructure-core-common.yaml

The CD pipeline automates Function App restarts if Docker images are retagged or if Terraform changes have been deployed.
This change similarly automates Web App restarts to significantly reduce support overhead.
Linked to:
- https://github.com/NHSDigital/dtos-devops-templates/pull/227
---

feat: DTOSS-10802 Automate Web App restarts in CD

---

tests/playwright-tests/src/tests/e2e/epic4c-add-participant-tests/epic4c-10011-10012-testsuite.spec.ts

test: 3881-merge-conflict-resolved

---

tests/playwright-tests/src/api/distributionService/bsSelectService.ts

test: 3881-fixed-invalid-url

---

tests/playwright-tests/src/tests/e2e/epic4c-add-participant-tests/epic4c-10011-10012-testsuite.spec.ts

test: fix-retry-on-test

---

.azuredevops/templates/cd-infrastructure-core-common.yaml
.github/workflows/cicd-1-pull-request.yaml

Minor updates to end to end deployment process to ensure correct stages run, and to push code to Sandbox following deployment to Dev. This is to evaluate sequential environment deployments.
Additional automation.
---

feat: DTOSS-9902 End to End Environment deployments updates

---

application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/MockedPDSData/complete-patient-9994276816.json
tests/playwright-tests/src/tests/e2e/epic4c-add-participant-tests/epic4c-testsuite-migrated.ts
tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-8425-01/ADDMANUAL1_BREAST_SCREENING_COHORT.json

Two new playwright tests
[DTOSS-10048](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10048)
[DTOSS-10050](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10050)
---

test: DTOSS-8425 outbound SNow e2e tests

---

tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-3881-02/AMENDMANUAL_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json

test: check-regression-failures

---

application/CohortManager/src/Functions/Shared/DataServices.Migrations/SeedData/ScreeningLkp.json

Adds the enrichment workflow id to the screening lkp table
[DTOSS-10978](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10978)
needed to support the manual add caas subscription process
---

feat: add enrichment cohort workflow

---

application/CohortManager/compose.core.yaml
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/production.tfvars
infrastructure/tf-core/environments/sandbox.tfvars

… and add manage-caas-subscription past dev
Configuration only change (in .tfvars and docker compose files) to replace manage-nems-subscription with manage-caas-subscription for all consumers. 
fixes https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10996 
Notes:
process-nems-update remains pointed at nems - it is specific to the nems implementation and not used in the current config.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive …

chore: DTOSS-10996 - move from manage-nems-subscription to manage-caas-subscription in all envs

---

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/ProcessFileClasses/ProcessCaasFile.cs
application/CohortManager/src/Functions/Shared/HealthChecks/Extensions/HealthCheckServiceExtensions.cs
tests/UnitTests/CaasIntegrationTests/processCaasFileTest/processCaasFileTests.cs

…rong
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-11012
---

fix: making error message better for understanding what is actually happening

---

.azuredevops/templates/cd-infrastructure-core-common.yaml

Previously deployed Slack alerting for the ADO pipelines was deficient in that it:
a) Could only send unformatted messages, which are harder to read than desired
b) Did not always alert for stage failures correctly
Improves pipeline run status visibility
---

fix: DTOSS-10921 Add Slack alerting to all stages of ADO deployment pipeline template

---

application/CohortManager/src/Functions/ParticipantManagementServices/ManageServiceNowParticipant/ManageServiceNowParticipantFunction.cs
tests/UnitTests/ParticipantManagementServicesTests/ManageServiceNowParticipantTests/ManageServiceNowParticipantFunctionTests.cs

[DTOSS-10996](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10996)
---

fix: Fixed log statement to avoid null object exception

---

application/CohortManager/src/Functions/Shared/Common/Extensions/MeshMailboxExtension.cs

Manage caas is throwing exception when its called.
function can start
---

fix: test fix for DI issue for manage caas 

---

application/CohortManager/src/Functions/DemographicServices/ManageCaasSubscription/ManageCaasSubscription.csproj
application/CohortManager/src/Functions/Shared/Common/Mesh/MeshSendCaasSubscribe.cs
tests/UnitTests/DemographicServicesTests/ManageCaasSubscriptionTests/MeshSendCaasSubscribeTests.cs
tests/integration-tests/MeshCaaSSubscribeIntegrationTests/SendCaasSubscribeTests.cs

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-11109 - Bug fix
Change message send format to be uncompressed
CaaS do not expect the format of the mesh message to be compressed. Changing the compression to be uncompressed
---

fix: caas send is uncompressed

---

application/CohortManager/src/Functions/Shared/HealthChecks/DatabaseHealthCheck.cs
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/integration.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/environments/preprod.tfvars
infrastructure/tf-core/environments/production.tfvars
infrastructure/tf-core/environments/sandbox.tfvars

- Added missing environment variable that was causing health check to fail
- Added log statement for exception
- Function health check was failing
---

fix: Fixed ParticipantManagementDataService HealthCheck

---

.azuredevops/pipelines/cd-infrastructure-int-core.yaml

Reinstate testTypes to avoid GitHub workflow failures
---

fix: reinstate testTypes to avoid GitHub workflow failures

---

infrastructure/tf-core/environments/production.tfvars
scripts/config/gitleaks.toml

update AUTH_CIS2_CLIENT_ID in production.tfvars for go live
---

chore: update AUTH_CIS2_CLIENT_ID in production.tfvars

---

infrastructure/tf-core/environments/production.tfvars

update AUTH_CIS2_ISSUER_URL for production environment
---

chore: update AUTH_CIS2_ISSUER_URL for production environment

---

application/CohortManager/src/Functions/Shared/DataServices.Database/DataServicesContext.cs
application/CohortManager/src/Functions/Shared/DataServices.Migrations/Migrations/20251007122006_add_unique_Screening_id_and_NHS_number_constraint.Designer.cs
application/CohortManager/src/Functions/Shared/DataServices.Migrations/Migrations/20251007122006_add_unique_Screening_id_and_NHS_number_constraint.cs

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-11210
---

fix: adding unique constraint for screening id and nhs number 

---

application/CohortManager/src/Functions/Shared/DataServices.Database/DataServicesContext.cs
application/CohortManager/src/Functions/Shared/DataServices.Migrations/Migrations/20251007132038_add_unique_nhs_number_demograpghic_table.Designer.cs
application/CohortManager/src/Functions/Shared/DataServices.Migrations/Migrations/20251007132038_add_unique_nhs_number_demograpghic_table.cs

https://nhsd-jira.digital.nhs.uk/browse/DTOSS-11230
---

fix: adding unique constraint for nhs number in demographic table

---

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json

[DTOSS-11237](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-11237)
---

feat: change referred transform rules to only run on add records
