.github/workflows/cicd-1-pull-request.yaml
This implements a GitHub action in which upon creating a PR the title checks to ensure the title adheres to the conventional commit standards. 
This ensures that all pull requests accurately describe the changes they have made
=> feat: adding a check for the use of conventional commits in pull request titles

application/CohortManager/src/Functions/CaasIntegration/processCaasFile/processCaasFile.cs, tests/CaasIntegrationTests/processCaasFileTest/processCaasFileTests.cs
When processing a caas file, any participants with unknown record types will be sent to the static validation function.
[DTOS-3006](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3006)
---
=> feat: Process unknown participant record types

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs
Set Cohort property on ValidationException to empty string.
Cohort property on ValidationException must not be null in order to be inserted into the database table.
---
=> fix: Set cohort property to empty string in LookupValidation

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs, application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/lookupRules.json, tests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs
- Implemented demographics lookup validation rule
- Combined AmendedParticipantMustExist and RemovedParticipantMustExist rules into ParticipantMustExist
- Changed LookupValidation response to BadRequest for when a valid LookupValidationRequestBody is not received 
[DTOSS-3477](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3477)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in …
=> feat: demographic data lookup validation rule

.azuredevops/cd-infrastructure.yaml
New condition in terraform apply stage of ADO infra cd pipeline - the apply stage will run only when run manually, not with every opened PR.
---
=> fix: manual build condition in terraform apply stage of ado infra cd pipeline

infrastructure/modules/azure-sql-server/database.tf, infrastructure/modules/shared-config/variables.tf
Previously the "UK South" location shortcut had a typo and was set to "SUK".
This changes it into "UKS" for all existing and further resources.
---
=> fix: changing the location shortcut to UKS

infrastructure/modules/shared-config/output.tf
Change the naming scheme of ACR from:
- lower("ACR${var.env}${var.location_map[var.location]}${var.application}") (acrdevukscohman)
to
- lower("ACR${var.location_map[var.location]}${var.application}${var.env}") (acrukscohmandev)
---
=> fix: acr naming scheme change with environment at the end

infrastructure/modules/shared-config/output.tf
A change to the naming scheme of API Management resources due to name conflict issue.
Change from: 
- lower("APIM-${var.application}-${var.env}-${var.location_map[var.location]}") (apim-cohman-dev-uks)
to
- lower("APIM-${var.env}-${var.application}-${var.location_map[var.location]}") (apim-dev-cohman-uks)
---
=> fix: change to the API Managemet name scheme

infrastructure/environments/development.tfvars.config, infrastructure/fnapp.tf, infrastructure/modules/function-app/locals.tf, infrastructure/modules/function-app/variables.tf, infrastructure/modules/storage/main.tf, infrastructure/modules/storage/output.tf, infrastructure/modules/storage/variables.tf, infrastructure/storage.tf, infrastructure/variables.tf
According to [DTOSS-3665](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3665):
- new storage account
- new container named 'file-exceptions'
- change in configuiration for the receiveCaasFile function app (caasfolder_STORAGE)
Required for a proper communication between the function and a storage account. 
---
=> feat: DTOSS-3665 - new storage account with container + change to ReceiveCaasFile fnapp config

infrastructure/environments/development.tfvars.config
This PR changes the DOCKER_ENABLE_CI flag value from False to True, so the docker images can be automatically processed after the update. 
---
=> feat: turn on the DOCKER_ENABLE_CI flag

infrastructure/environments/development.tfvars.config, infrastructure/modules/function-app/locals.tf
This PR includes:
- renaming a few of the function apps to be consistent across the whole solution
- adding missing environmental variables for a few functions, based on the input from Martin
Current list of the function apps after implementing this change:
`<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/macmur/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/macmur/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtm …
=> fix: renamed function apps and added missing env variables

infrastructure/modules/function-app/locals.tf
This PR adds the missing `ExceptionFunctionURL` variable to ReceiveCaasFile function.
The missing variable has been already added via portal, this terraform update reflect those changes.
---
=> fix: add the ExceptionFunctionURL variable to ReceiveCaasFile function

application/CohortManager/src/Functions/CaasIntegration/processCaasFile/processCaasFile.cs, tests/CaasIntegrationTests/processCaasFileTest/processCaasFileTests.cs
This PR is adding validation logic in order to make sure date fields within participant records with dates are not set to future dates. Also handles cases where the date fields are null.
The aim is to prevent processing participant records with dates that are mistakenly set in the future, leading to data inconsistencies or errors in the system.
Logic added is the following:
- `TryParseDate` method is converting the string version of a date into DateTime object.
- `IsValidDate` method checks if the date is either null or not in the future.
- If any date fails validation, participant record is skipped.
--- …
=> feat: DTOSS-3834 - Date Validation for Participant Data Fields

application/CohortManager/src/Functions/CaasIntegration/processCaasFile/processCaasFile.cs
…as file so retries do not occour
now  returns created when file validation fails for a single record 
---
=> fix: now returns created when creating a validation log in process caas file

application/CohortManager/src/Functions/CaasIntegration/processCaasFile/processCaasFile.cs
…hen there is a sinngle error stoppig records form being processed
now returns created when there is an erorr and does not return when there is a single error stopping records form being processed 
---
=> fix: returning correctly

infrastructure/appinsights.tf, infrastructure/baseline.tf, infrastructure/environments/development.tfvars.config, infrastructure/law.tf, infrastructure/modules/app-insights/output.tf, infrastructure/modules/baseline/base-rg.tf, infrastructure/modules/baseline/outputs.tf, infrastructure/modules/baseline/variables.tf, infrastructure/modules/log-analytics-workspace/output.tf, infrastructure/variables.tf
This PR is a part of DTOSS-3653 and includes a fix to create a new Resource Group in the Dev Audit subscription.
Along with implementing it, I will recreate AppInsights and LAW in the new subscription.
Switching Function Apps to new AI/LAW will have it's own PR. 
---
=> fix: DTOSS-3653 create Resource Group in audit subscription

application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs, application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs, application/CohortManager/src/Functions/Shared/Data/Database/IParticipantManagerData.cs, application/CohortManager/src/Functions/Shared/Data/Database/ParticipantManagerData.cs, application/CohortManager/src/Functions/screeningDataServices/createParticipant/createParticipant.cs, application/CohortManager/src/Functions/screeningDataServices/markParticipantAsIneligible/markParticipantAsIneligible.cs, application/CohortManager/src/Functions/screeningDataServices/updateParticipantDetails/updateParticipantDetails.cs, tests/CohortDistributionTests/CreateCohortDistributionTests/CreateCohortDistributionTests.cs, tests/ParticipantManagementServicesTests/addParticipantTest/AddParticipantTestClass.cs, tests/screeningDataServicesTests/MarkParticipantAsIneligibleTests/MarkParticipantAsIneligibleTests.cs, tests/screeningDataServicesTests/updateParticipantDetailsTests/updateParticipantDetails.cs
Changed the lookup function for pulling participants from the participant management table to use both the NHS Number and the ScreeningId
[DTOSS-4049](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-4049)
---
=> feat: DTOSS-4049 participant lookup by NHS Number and Screening Id

application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs
When testing the below bug ticket, I noticed the interpreter field was not being inserted correctly into the cohort distribution table. This PR fixes that issue.
The `49.InterpreterCheck.NonFatal` static rule is working as expected when I have tested it locally.
[DTOSS-3843](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3843)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this …
=> fix: insert interpreterRequired into cohort distribution table correctly

infrastructure/environments/development.tfvars.config, infrastructure/environments/nft.tfvars.config
A quick fix for a typo in the `inbound-poison` (previously `inbound-posion`) container in the file-exceptions storage account in both Dev and NFT.
---
=> fix: a proper name for the inbound-poison container in file-exception sa

.tool-versions
Upgrade to the `Terraform` version used by `MAKE` tools in the repo. 
Previous version: `1.5.7`
Current version: `1.9.6`
---
=> fix: new terraform version for make tools

application/CohortManager/rules/Breast_Screening_cohortRules.json, application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs, tests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs
- fixed the demographics rule bug
- renamed rule to TooManyDemographicsFieldsChanged
[DTOSS-4755](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-4755)
---
=> fix: demographics rule

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformAction.cs, application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json, application/CohortManager/src/Functions/Shared/Model/TransformFields.cs
As part of the below ticket, some new transformation rules need to transform multiple fields rather than just one (which is the current functionality). 
This PR includes the refactor work required to allow this. A future PR will add the new rules.
Basically I've refactored the "Context" object on the "TransformAction" of the rules to use an array of fields, which will allow multiple fields to be added. Then refactored the `TransformAction` class to handle this new array.
[DTOSS-4771](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-4771)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-ben …
=> feat: allow multiple transformations per rule

application/CohortManager/rules/Breast_Screening_cohortRules.json, tests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs
Removed validation rule 67 for HMP and MHI from cohort_rules.json and removed the associated unit tests
---
=> feat: Remove validation rule 67 for HMP and MHI

application/CohortManager/src/Functions/Shared/Common/ReceiveCaasFileHelper.cs
Remove hardcoded values for gender and death status when mapping the parquet file to participant object and use the supplied values instead.
[DTOSS-5646](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5646)
---
=> fix: remove hardcoded Gender and DeathStatus

application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/Breast_Screening_staticRules.json, tests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.cs
Postcode validation rule was throwing exceptions when its null or empty
---
=> fix: postcode null bug

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_lookupRules.json
primary care provider rules did not allow for null values which was incorrect
---
=> fix: primary care provider rules now allow for null

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.cs
Change batching logic to just use a batch size. 
Fixes issues where batch size would be set to zeo
---
=> fix: refactor batching to use batch size to set batch size

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json, tests/UnitTests/TransformDataServiceTests/TransformDataServiceTests.cs
Fixes a bug where the RetrieveBSOCode db lookup was trying to use a null postcode.
---
=> fix: prevent RetrieveBSOCode lookup with null postcode

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs, application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformString.cs
A couple of minor changes in here: 
1. Small change to use the error message from the character transformation rule when we encounter the `\E\` or `\T\` special cases when raising the exception.
2. Another change to show the exception in the warning log in the `TransformDataServices` function.
---
=> fix: surface transform string error in exception

application/CohortManager/Set-up/azurite/Dockerfile, application/CohortManager/Set-up/azurite/azurite-setup.py, application/CohortManager/compose.yaml
- Removed the part of the azurite setup where rules are added
- Removed duplicate env variable in the compose.yaml
Rules were moved out of the rules folder into the respective function's folder, but the azurite setup script was not updated accordingly
---
=> fix: azurite setup script not updated after rule move

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformString.cs, tests/UnitTests/TransformDataServiceTests/TransformDataServiceTests.cs
- Changed exception type so exceptional chars are handled correctly
- Added tests for exceptional chars
Illegal characters that do not have a transformation rule should raise an exception if they are found, this was happening but the exception message was not being sent to the DB
[DTOSS-6054](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6054)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your …
=> fix: some illegal chars not throwing exceptions

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json, application/CohortManager/src/Functions/Shared/Data/Database/BsTransformationLookups.cs
- DB Lookup for Invalid Flag was using participant ID which is not consistent between Participant_managment and Participant_Demographic
[DTOSS-6184](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6184)
---
=> fix: reason for removal bug fix

infrastructure/environments/development.tfvars.config, infrastructure/environments/nft.tfvars.config, scripts/deployment/get-docker-names.sh
This PR includes the Development/NFT infra definition of the new function used by Cohort Manager: `participant-demographic-data-service-configuration`.
Successful Dev plan:
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=10442&view=logs&j=ced2749f-787a-529b-d064-72b5c61df22f&t=a8ef944f-7917-542a-f805-14b39eb0c11c
Successful NFT plan:
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=10443&view=logs&j=ced2749f-787a-529b-d064-72b5c61df22f&t=a8ef944f-7917-542a-f805-14b39eb0c11c
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting- …
=> feat: dev/nft participant-demographic-data-service configuration

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/DataLookupFacade.cs
Minor change to the logic for lookup rule 58.
The db lookup no longer needs to check `INCLUDED_IN_COHORT = "Y"`
Also there's a few formatting changes / sonar lint warning fixes in here too.
[DTOSS-6291](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6291)
---
=> fix: remove included in cohort check for lookup rule 58

infrastructure/tf-audit/variables.tf, tests/UnitTests/ScreeningDataServicesTests/ValidationExceptionDataTests/GetValidationExceptionTests/GetValidationExceptionsTests.cs, tests/UnitTests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.cs, tests/UnitTests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.csproj
Adds a unit test to increase the coverage on static validation.
Also formatted a terraform file that was failing the pipeline lint check.
Also fixes a couple of failing unit tests.
[DTOSS-6391](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6391)
---
=> test: increase coverage on static validation

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_lookupRules.json, tests/UnitTests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs
This PR makes the following changes to the existing lookup rule `36.CurrentPostingAndPrimaryProvider.NonFatal`:
1. Renames it to `3645.CurrentPostingAndPrimaryProvider.NonFatal`. This is to differentiate this rule from the other rule 36, and use the rule number 45 from the spreadsheet.
2. Adds this new logic:
- IF `posting_category` is either "ENGLAND", "DMS" or "IOM"
- AND the `primary_care_provider` is !null
- AND the `primary_care_provider` is not in the lookup table
- THEN raise exception
3. Updates unit tests
[DTOSS-6291](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6291)
--- …
=> fix: rename lookup rule 36 and update logic 

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_cohortRules.json, application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs, application/CohortManager/src/Functions/screeningDataServices/ExcludedSMULookupDataService/ExcludedSMULookupDataServices.cs, tests/UnitTests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs
Fixes an error when rule 51 receives a null primary care provider.
This is valid and should not cause rule 51 to raise an exception.
Updates the unit tests to reflect this.
Also removes some temp logging in LookupValidation function.
And fixes the URL in Excluded SMU lookup.
---
=> fix: check for null primary care provider before excluded SMU db lookup

tests/UnitTests/ScreeningDataServicesTests/MarkParticipantAsIneligibleTests/MarkParticipantAsIneligibleTests.cs
Added new tests to increase test coverage to 84%.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6456
---
=> fix: dtoss 6456 increase unit test coverage mark participant as ineligible

application/CohortManager/src/Functions/Shared/Common/Utilities/ReflectionUtilities.cs, application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceClient.cs, application/CohortManager/src/Functions/Shared/DataServices.Client/IDataServiceClient.cs, application/CohortManager/src/Functions/Shared/DataServices.Core/DataServiceAccessor.cs, application/CohortManager/src/Functions/Shared/DataServices.Core/Exceptions/MultipleRecordsFoundException.cs, application/CohortManager/src/Functions/Shared/DataServices.Core/RequestHandler.cs, tests/UnitTests/DataServiceTests/BsSelectGpPracticeDataServiceTests.cs, tests/UnitTests/DataServiceTests/DataServiceClientTests.cs
Adds the ability to get a single record by a filter to the Data Services Client and Data Services Core
[DTOSS-6585](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6585
---
=> feat: DTOSS-6585 get single by filter

application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs
1st request not returning 2nd due to time logic 
SQL refactored to include all statusCodes Except 204 no content 
Bug raised by testers exposed 1st requestId issue. 
---
=> fix: 1st requestId Bug

application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs
Changed from returning null from method to Rethrowing exception.
By returning null this was causing a null reference exception which is misleading given it was an http exception.
As the exception couldn't be handled in the catch block we will just re-throw the exception so it doens't cause further misleading exception.
---
=> fix: unhandled exception being caught

application/CohortManager/src/Functions/CohortDistributionServices/RetrieveCohortDistribution/RetrieveCohortDistribution.cs, application/CohortManager/src/Functions/Shared/Common/Interfaces/ICreateCohortDistributionData.cs, application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs, application/CohortManager/src/Functions/Shared/Model/CohortDistributionParticipant.cs, tests/UnitTests/CohortDistributionTests/CohortDistributionDataTests/AddCohortDistributionTests.cs
Removed ScreeningServiceId as we are only calling BS table 
Updated tests 
Updated documentation 
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6726
https://nhsd-confluence.digital.nhs.uk/display/DTS/%3C%3CWIP%3E%3E+Release+0+Cohort+Manager+API+Design
---
=> fix: Removed screeningServiceId and references 

application/CohortManager/src/Functions/CaasIntegration/RetrieveMeshFile/RetrieveMeshFile.cs, application/CohortManager/src/Functions/ParticipantManagementServices/addParticipant/addParticipant.cs, application/CohortManager/src/Functions/Shared/Common/AzureQueueStorageHelper.cs, application/CohortManager/src/Functions/Shared/Common/EnumHelper.cs
=> fix: addressing comments made my sonnar cube

application/CohortManager/src/Functions/ExceptionHandling/CreateException/CreateException.cs, application/CohortManager/src/Functions/Functions.sln, tests/UnitTests/ExceptionHandlingTests/CreateExceptionTests/CreateExceptionTests.cs, tests/UnitTests/ExceptionHandlingTests/CreateExceptionTests/CreateExceptionTests.csproj
Adds 100% unit test coverage to `CreateException` function.
Note: the changes to `CreateException` are the same as in my other open [PR](https://github.com/NHSDigital/dtos-cohort-manager/pull/565). This PR simply adds a new test project for coverage.
---
=> test: add CreateException unit tests

application/CohortManager/src/Functions/Shared/Common/MeshToBlobTransferHandler.cs, tests/UnitTests/TransformDataServiceTests/TransformDataServiceTests/TransformDataServiceTests.cs
chunked mesh files were saving with incorrect name
Change to use namefunction to name the file
---
=> fix: mesh file name bug

infrastructure/tf-core/diagnostic_settings.tf
Remove SQLSecurityAuditEvents log category due to PII data being included in log entries.
The SQLSecurityAuditEvents log entries include the SQL statement that triggered the log entry creation and often this includes potentially sensitive information.
---
=> fix: DTOSS-5205 Remove SQLSecurityAuditEvents due to PII data being included in log entries

.github/actions/scan-secrets/action.yaml, application/CohortManager/src/Functions/Shared/Rebuild.me, scripts/githooks/scan-secrets.sh
Amend Git Leaks Scanning to only check Current Branch as present config means that any pushed branch can stop all pipelines from failing.
---
=> fix: Amend Git Leaks Scanning to only check Current Branch

application/CohortManager/src/Functions/screeningDataServices/markParticipantAsEligible/markParticipantAsEligible.cs, tests/UnitTests/ScreeningDataServicesTests/MarkParticipantAsEligibleTests/MarkParticipantAsEligibleTests.cs
In the markParticipantAsEligible function, the participantId was always null when trying to get the participant, so I've changed it to use GetSingleByFilter with the NHS number instead. 
---
=> fix: markParticipantAsEligible function to use NHS number to get participant

application/CohortManager/src/Functions/screeningDataServices/markParticipantAsEligible/markParticipantAsEligible.cs, application/CohortManager/src/Functions/screeningDataServices/markParticipantAsIneligible/markParticipantAsIneligible.cs, tests/UnitTests/ScreeningDataServicesTests/MarkParticipantAsEligibleTests/MarkParticipantAsEligibleTests.cs, tests/UnitTests/ScreeningDataServicesTests/MarkParticipantAsIneligibleTests/MarkParticipantAsIneligibleTests.cs
Fix:- Use both NHS number and ScreenId to filter and update eligibility flag of participant.
---
=> fix: use NHS number and ScreenId to update eligibility flag

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/ProcessFileClasses/ProcessCaasFile.cs, application/CohortManager/src/Functions/Shared/Data/Database/ValidationExceptionData.cs, application/CohortManager/src/Functions/Shared/Model/EFModels/ParticipantDemographic.cs, application/CohortManager/src/Functions/Shared/Model/Participant.cs, application/CohortManager/src/Functions/screeningDataServices/markParticipantAsIneligible/markParticipantAsIneligible.cs, tests/UnitTests/ScreeningDataServicesTests/ValidationExceptionDataTests/ValidationExceptionDataTests/ValidationExceptionDataTests.cs
- Ensures all uses of the filter function in the data service doesnt have a .ToString()
- Sorts issue with ParticipantDemographicDataService where we couldn't filter on NHSNumber as it was nullable
Bug Fixes
---
=> fix: to string issue

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json
The expected transformation for `ReasonForRemovalEffectiveFromDate` on the `00.Other.InvalidFlag.TrueAndNoPrimaryCareProvider` rule was not happening. 
The date string was failing to parse in the databaseHelper ParseDates method.
Adding an expected format to the date string in the rule fixed the issue.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7129
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really …
=> fix: add date format to transformation rule

application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/ProcessFileClasses/ProcessCaasFile.cs, application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs, tests/UnitTests/CaasIntegrationTests/processCaasFileTest/processCaasFileTests.cs, tests/UnitTests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs
- Adds new logic into LookupValidation function that will prevent all the common lookup rules being run for DEL records.
- DEL records should only ever run the DEL workflow.
- This functionality is only active when the "AllowDeleteRecords" is set true, so will not affect current behaviour.
- I have tested this by calling `updateParticipant` from `ProcessCaasFile`. This was just so I could easily trigger lookup validation.
- A future PR will implement further logic in the RemoveParticipant function, and replace the call to `updateParticipant`.
[DTOSS-6335](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6335)
--- …
=> feat: prevent running common lookup rules for del records

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json, tests/UnitTests/TransformDataServiceTests/TransformDataServiceTests/TransformDataServiceTests.cs
- Updates the invalid flag transform rule to also trigger when a del record is processed.
- When a del record is allowed to be processed, the same data transformation as the invalid flag rule is required to be made.
[DTOSS-6335](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6335)
---
=> feat: update invalid flag transform rule to trigger for del records

application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceClientBuilder.cs
Improved the error message for when a data service is missing the url
easier to debug
---
=> fix: better data service error message

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs, application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformString.cs, application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_cohortRules.json, application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/LookupValidation.cs, application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/StaticValidation.cs
- Turned off fast compiler for the rules
There was a bug in the rules engine where it would fail to parse some rules when evaluating the first participant after startup
[DTOSS-7561](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7561)
---
=> fix: rules engine startup bug

application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/Breast_Screening_staticRules.json, tests/UnitTests/ScreeningValidationServiceTests/StaticValidation/StaticValidationTests.cs
- improved the regex for the postcode check in static validation
discovered the postcode regex does not cover all possible postcodes
---
=> fix: improve regex for postcode validation

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformAction.cs, application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json
Fixes an issue where the transform function was unable to evaluate the `databaseParticipant` for both the `family_name` and the `given_name`.
[DTOSS-7634](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7634)
---
=> fix: existing family and given name transformation not applied

application/CohortManager/src/Functions/Shared/Data/Database/DatabaseHelper.cs, application/CohortManager/src/Functions/Shared/Data/Database/IDatabaseHelper.cs, application/CohortManager/src/Functions/Shared/Model/Participant.cs, application/CohortManager/src/Functions/Shared/Utilities/MappingUtilities.cs, application/CohortManager/src/Functions/screeningDataServices/createParticipant/createParticipant.cs
- Refactored create participant to use the standard ToParticipantManagment method rather than using custom logic in the class
- Created a centralized ParseStringFlag method instead of relying on individual implementations
---
=> refactor: move create participant to use ToParticipantManagment

application/CohortManager/src/Functions/ScreeningValidationService/StaticValidation/Breast_Screening_staticRules.json
- added a null check for rule 17: date of birth
Improper handling of nulls was causing static validation to return a 500 when the rule should just fail
---
=> fix: null handling for rule 17

.github/workflows/cicd-1-pull-request.yaml
A change that will switch Team Select CI process from using an internal version of `.github/workflows/stage-3-build-images.yaml` and `scripts/deployment/get-docker-names.sh` files to using the ones from [Template repository](https://github.com/NHSDigital/dtos-devops-templates/pull/116), with a support for curating a list of docker image to build based on multiple compose.yaml files.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive …
=> feat: enabling the new docker image building script in Cohort Manager

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_cohortRules.json, application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/DataLookupFacadeBreastScreening.cs, tests/UnitTests/ScreeningValidationServiceTests/LookupValidation/DataLookupFacadeBreastScreeningTests.cs, tests/UnitTests/ScreeningValidationServiceTests/LookupValidation/LookupValidationTests.cs, tests/UnitTests/TransformDataServiceTests/TransformDataServiceTests/TransformDataLookupFacadeTests.cs
Rule 51 fails to execute when the current posting is null on either existing or new participant.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7841
---
=> fix: rule 51 null exception

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/DataLookupFacadeBreastScreening.cs
Missing Postcode fix for outcode lookup in lookup rules
---
=> fix: outcode postcode spliting

tests/UnitTests/DataServiceTests/DataServiceTests.csproj, tests/UnitTests/DataServiceTests/ScreeningLkpDataServiceTests.cs
Adds 100% unit test coverage for ScreeningLkpDataService.
[DTOSS-7857](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7857)
---
=> test: add unit test coverage for ScreeningLkpDataService

application/CohortManager/compose.deps.yaml
If the azure storage SDK and azurite have different API versions, it causes an exception in receive caas file
---
=> fix: azurite error with api version

.github/workflows/cicd-1-pull-request.yaml, .github/workflows/cicd-2-publish.yaml, application/CohortManager/src/Functions/Shared/rebuild.all
A fix to be able to run the image building process straight from the `cicd-1-pull-request.yaml` workflow instead of using the `cicd-2-publish.yaml` one, which was still referencing the old `.github/workflows/stage-3-build.yam`l file.
---
=> fix: DTOSS-7928 fix the trigger to run the image building process workflow

application/CohortManager/compose.core.yaml, application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/transformRules.json
Changed transform rule 3 date of death not null with RFR != DEA to use `string.IsNullOrEmpty()`
The transformation rule was triggering for every participant because the rule used != null instead of !string.IsNullOrEmpty
[DTOSS-7811](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7811)
---
=> fix: change rule to use IsNullOrEmpty

application/CohortManager/src/Functions/ExceptionHandling/CreateException/CreateException.cs, tests/UnitTests/ExceptionHandlingTests/CreateExceptionTests/CreateExceptionTests.cs
- changed create exception to return OK instead of CREATED
In a previous PR, create exception was changed to return CREATED to fix a sonarqube issue, but the exception handler client expects an OK response, so this was causing the create exception request to be logged as a failure
---
=> fix: create exception returning the wrong HTTP code

infrastructure/tf-core/environments/preprod.tfvars
Revert IsExtractedToBSSelect to false for second stage of parallel run.
---
=> feat: dtoss-7765: Revert IsExtractedToBSSelect to false

application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
there was a check for ignore participant exceptions if the participant failed static or lookup validation but not cohort validation
---
=> fix: cohort rule exceptions now able to be ignored

application/CohortManager/src/Functions/Functions.sln, tests/UnitTests/ParticipantManagementServicesTests/GetParticipantReferenceDataTests/GetParticipantReferenceDataTests.cs, tests/UnitTests/ParticipantManagementServicesTests/GetParticipantReferenceDataTests/GetParticipantReferenceDataTests.csproj
Updated and improved automated tests to include Component tests (Happy and Unhappy paths) and unit tests for GetParticipantReferenceData.
Achieved 100% test coverage
PFB jira link:
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8096
---
=> feat: DTOSS-8096 GetParticipantReferenceData test coverage

.github/workflows/stage-2-test.yaml, scripts/config/sonar-scanner.properties
Adds coverage reporting with minor changes to the parallelised unit test workflow. The report can set a coverage threshold gate per individual test. This remains disabled for the time being, since some tests currently have low coverage. The combined coverage report is also rendered in VisualStudio XML format, for ingestion by SonarQube Cloud.
Worked examples tend to show either parallel unit tests **or** exporting coverage reports to SonarQube Cloud - but not, it seems, both. Most combined coverage reports sacrifice test parallelism.
This was very difficult to get working owing to SonarQube Cloud not supporting Cobertura format test-coverage reports, and by the scarcity of tools that can merge multiple reports after parallelised testing runs. Most tools fail to fit this use case because: …
=> feat: DTOSS-8151 add test coverage reporting to parallelised unit tests

application/CohortManager/src/Functions/Shared/Data/Database/CreateCohortDistributionData.cs
When there is no next batch available on get cohort distribution, this will return no longer cause a null reference exception.
This will return the next batch available.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8369
Bug where when there is not next batch and a request is made with a request id then the API will return a 500 error.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your …
=> fix: no next batch fix

infrastructure/tf-core/environments/development.tfvars, infrastructure/tf-core/environments/integration.tfvars, infrastructure/tf-core/environments/nft.tfvars, infrastructure/tf-core/environments/preprod.tfvars
To avoid multiple instances of the RetrieveMeshFile function from running in parallel, this function needs breaking out into its own App Service Plan across all environments.
---
=> feat: Move RetrieveMeshFile function to dedicated App Service plan

infrastructure/tf-core/environments/development.tfvars, infrastructure/tf-core/environments/integration.tfvars, infrastructure/tf-core/environments/nft.tfvars, infrastructure/tf-core/environments/preprod.tfvars
Update to PR #910 as cannot set scaling min, max and default all to the same value. Re-use values set for High Load Functions plan.
---
=> feat: Move RetrieveMeshFile to dedicated plan - scaling fix

application/CohortManager/src/Functions/CohortDistributionServices/CreateCohortDistribution/CreateCohortDistribution.cs
Service provider was being logged to the exception table instead of screening Name, This caused issues with resolving exceptions when an amend is received. 
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8518
Correct logging and removal of exceptions.
---
=> fix: correct wrong screening name logged to exception table

infrastructure/tf-core/rbac.tf, infrastructure/tf-core/storage.tf
In order for dotnet durable functions to access their underlying storage accounts when public access to the storage account is disabled, a private endpoint for the storage account table service must be deployed, along with the Table Contributor RBAC role..
Allows increased security compliance.
---
=> feat: Add Private Endpoints for Storage Tables

.github/actions/perform-static-analysis/action.yaml, .github/workflows/stage-2-analyse.yaml, scripts/reports/sonar-analysis.sh
I am adding a dotnet test step in between sonar scan start and end to attempt to fix coverage reporting. Can only test this fix in main.
---
=> feat: DTOSS-7817 - Adding dotnet test step in between sonar scan start and end to attempt to fix coverage reporting

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/DataLookupFacadeBreastScreening.cs
Outcode lookup was calling an async method without getting the result so the task was returned and the outcode check failed
[DTOSS-9100](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9100)
---
=> fix: outcode lookup

tests/TestUtils/MockHelpers.cs
…ing method in MockHelpers class
Chore: changing stream over to memory stream in GenerateStreamFromString method in MockHelpers class)
https://sonarcloud.io/project/issues?open=AZbYoO08J-J0UbUiw6Md&id=NHSDigital_dtos-cohort-manager
---
=> chore: changing stream over to memory stream in GenerateStreamFromString method in MockHelpers class

application/CohortManager/src/Functions/ScreeningValidationService/LookupValidation/Breast_Screening_cohortRules.json
adds an extra null check for rule 54 before checking if the primary care provider is null
Rule was previously erroring if there were two amends send in a row with a null PCP
---
=> fix: add null check

application/CohortManager/src/Functions/Shared/DataServices.Migrations/Migrations/20250707144132_remove-ceased-flag.Designer.cs, application/CohortManager/src/Functions/Shared/DataServices.Migrations/Migrations/20250707144132_remove-ceased-flag.cs, application/CohortManager/src/Functions/Shared/Model/EFModels/ParticipantManagement.cs, application/CohortManager/src/Functions/Shared/Model/Participant.cs
This PR removes the CEASED_FLAG column from the PARTICIPANT_MANAGEMENT table via a proper EF Core migration. The migration drops the column cleanly from the database schema.
I removed the column in the Participant model and the ParticipantManagement EF Model manually
After that, I ran the migration. 
The CEASED_FLAG column is no longer needed and should be removed from the table. Previously, this column was removed manually in a prior PR, but to maintain proper database version control and consistency, this PR implements the removal through a formal EF Core migration.
--- …
=> fix: Remove Ceased Flag from Participant Management table

application/CohortManager/src/Web/package.json
Remove the Next.js `--turbopack` build command as it seems temperamental. 
---
=> fix: remove turbopack from the build command

infrastructure/tf-core/environments/nft.tfvars
Adding missing configuration and environmental variables for `ManageNemsSubscription` function in NFT environment:
```
key_vault_url          = "KeyVaultConnectionString"
"ManageNemsSubscription--NemsFhirEndpoint" = "https://msg.intspineservices.nhs.uk/STU3"
"ManageNemsSubscription--FromAsid" = "200000002527"
"ManageNemsSubscription--ToAsid" = "200000002527"
"ManageNemsSubscription--NemsKeyName" = "nems-client-certificate"
"ManageNemsSubscription--SubscriptionProfile" = "https://fhir.nhs.uk/STU3/StructureDefinition/EMS-Subscription-1"
"ManageNemsSubscription--SubscriptionCriteria" = "https://fhir.nhs.uk/Id/nhs-number"
"ManageNemsSubscription--BypassServerCertificateValidation" = "false"
```
Successfully planned and applied in this PL run: …
=> fix: missing environmental variables in NFT

application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs, application/CohortManager/src/Functions/Shared/Common/ExceptionHandler.cs, application/CohortManager/src/Functions/Shared/Common/Interfaces/IExceptionHandler.cs, tests/UnitTests/TransformDataServiceTests/TransformDataServiceTests/TransformDataServiceTests.cs
Fixes a bug where a Name prefix transform (LIEUTENANT COLONEL) was logging with an incorrect category (13)
This now logs correctly to category (11)
Bug Fix
[DTOSS-10192](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10192)
---
=> fix: Incorrect Category for name prefix transform

infrastructure/tf-core/environments/development.tfvars, infrastructure/tf-core/environments/integration.tfvars, infrastructure/tf-core/environments/nft.tfvars, infrastructure/tf-core/environments/preprod.tfvars, infrastructure/tf-core/environments/production.tfvars
Each environment now has its own WAFv2 Policy for Azure Front Door.
It transpires that a single WAF policy cannot be associated with multiple AFD Security Policies within one Front Door Profile.
Since the associations cannot be managed in a granular manner, other than at the creation of the Front Door Security Profile, this requires unnecessary proliferation of WAF policies to avoid entangling separate SDLC environments. There is no cost impact, but their ongoing management will unfortunately be multiplied (for rule exemptions, IP whitelisting etc.). This does appear to be a significant design oversight by Microsoft.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal …
=> fix: DTOSS-10352 WAF policy collisions

application/CohortManager/src/Functions/NemsSubscriptionService/NemsMeshRetrieval/NemsMeshRetrieval.cs, application/CohortManager/src/Functions/NemsSubscriptionService/NemsMeshRetrieval/NemsMeshRetrievalConfig.cs, application/CohortManager/src/Functions/NemsSubscriptionService/NemsMeshRetrieval/Program.cs, infrastructure/tf-core/environments/development.tfvars, infrastructure/tf-core/environments/integration.tfvars, infrastructure/tf-core/environments/nft.tfvars, infrastructure/tf-core/environments/preprod.tfvars, infrastructure/tf-core/environments/production.tfvars, infrastructure/tf-core/environments/sandbox.tfvars, tests/UnitTests/NemsSubscriptionServiceTests/NemsMeshRetrievalTests/NemsMeshRetrievalTests.cs
Added NEMS-specific prefixes to all MESH configuration properties to fully separate NEMS and CAAS authentication/certificate configuration.
**JIRA Ticket:** [DTOSS-9694](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9694)
Changes include:
- Added `NemsMesh` prefix to all remaining configuration properties (API base URL, certificates, authentication) in NEMS Mesh Retrieval service
- Updated Program.cs to use the new NEMS-specific configuration properties
- Updated all environment configuration files to include the new prefixed properties
- Updated unit tests to reflect configuration changes
Following the mailbox configuration separation, this change completes the configuration isolation by ensuring NEMS MESH functions use completely separate configuration properties for certificates, …
=> fix: added NemsMesh prefix to all config values in NemsMeshRetrieval function - separating from RetrieveMeshFile

application/CohortManager/compose.core.yaml, application/CohortManager/src/Functions/ParticipantManagementServices/ManageServiceNowParticipant/ManageServiceNowParticipantFunction.cs, application/CohortManager/src/Functions/ServiceNowIntegration/ServiceNowMessageHandler/IServiceNowClient.cs, application/CohortManager/src/Functions/ServiceNowIntegration/ServiceNowMessageHandler/Models/SendServiceNowMessageRequestBody.cs, application/CohortManager/src/Functions/ServiceNowIntegration/ServiceNowMessageHandler/Models/ServiceNowResolutionRequestBody.cs, application/CohortManager/src/Functions/ServiceNowIntegration/ServiceNowMessageHandler/ReceiveServiceNowMessageFunction.cs, application/CohortManager/src/Functions/ServiceNowIntegration/ServiceNowMessageHandler/SendServiceNowMessageFunction.cs, application/CohortManager/src/Functions/ServiceNowIntegration/ServiceNowMessageHandler/ServiceNowClient.cs, application/CohortManager/src/Functions/ServiceNowIntegration/ServiceNowMessageHandler/ServiceNowMessageHandlerConfig.cs, application/CohortManager/src/Functions/ServiceNowIntegration/ServiceNowMessageHandler/ServiceNowMessageTemplates.cs, application/CohortManager/src/Functions/Shared/Model/ServiceNowParticipant.cs, infrastructure/tf-core/environments/development.tfvars, infrastructure/tf-core/environments/integration.tfvars, infrastructure/tf-core/environments/nft.tfvars, infrastructure/tf-core/environments/preprod.tfvars, infrastructure/tf-core/environments/production.tfvars, infrastructure/tf-core/environments/sandbox.tfvars, tests/UnitTests/ParticipantManagementServicesTests/ManageServiceNowParticipantTests/ManageServiceNowParticipantFunctionTests.cs, tests/UnitTests/ServiceNowMessageHandlerTests/ReceiveServiceNowMessageFunctionTests.cs, tests/UnitTests/ServiceNowMessageHandlerTests/SendServiceNowMessageFunctionTests.cs, tests/UnitTests/ServiceNowMessageHandlerTests/ServiceNowClientTests.cs
- Maps the internal message types to outbound SNow API requests
- Replaces all mention of sys Id with case number
[DTOSS-8425](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8425)
---
=> feat: Mapped internal message types to outbound SNow API requests

infrastructure/tf-core/environments/development.tfvars, infrastructure/tf-core/environments/integration.tfvars, infrastructure/tf-core/environments/nft.tfvars, infrastructure/tf-core/environments/preprod.tfvars, infrastructure/tf-core/environments/production.tfvars, infrastructure/tf-core/environments/sandbox.tfvars
Fixed ProcessNemsUpdate function storage configuration to correctly connect to storage account and monitor the proper blob container for NEMS updates.
**JIRA Ticket:** [DTOSS-9294](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9294)
Changes include:
**Storage Configuration Fix:**
- Changed `storage_account_env_var_name` from
`caasfolder_STORAGE` to `nemsmeshfolder_STORAGE` in all environment tfvars files
- Changed container name from `nems-messages` to
`nems-updates` to match function blob trigger
- Applied fixes across all 6 environments: development, sandbox, nft, integration, preprod, production
The ProcessNemsUpdate function had a critical
storage configuration mismatch that prevented it
from functioning:
1. **Storage Connection Issue**: Function expected connection string in …
=> fix: corrected terraform for ProcessNemsUpdate to fix the storage connection

application/CohortManager/src/Functions/Shared/Common/Extensions/HttpClientExtension.cs, application/CohortManager/src/Functions/Shared/Common/PdsHttpClientMock.cs, tests/UnitTests/SharedTests/HttpClientFunctionTests/PdsHttpClientMockTests.cs
Fixed critical JSON deserialisation error in ProcessNemsUpdate function caused by incorrect mock data type, and improved naming clarity of PDS-specific mock implementation.
Changes include:
**Bug Fix:**
- Fixed `PdsHttpClientMock.SendGet` method to return `PdsDemographic` instead of `ParticipantDemographic`
- Resolves JSON deserialization error: "The JSON value could not be converted to System.String. Path: $.ParticipantId"
**Naming Improvements:**
- Renamed `HttpClientFunctionMock` to `PdsHttpClientMock` to reflect PDS-specific purpose
- Renamed test file `HttpClientFunctionMockTests` to `PdsHttpClientMockTests`
- Added comprehensive XML documentation explaining PDS-specific usage
**Test Coverage:**
- Added 13 unit tests for `PdsHttpClientMock` that validate correct JSON serialization
- …
=> fix: corrected pds mock data type, added unit tests, renamed mock implementation

application/CohortManager/src/Functions/Shared/Common/PdsHttpClientMock.cs, application/CohortManager/src/Functions/Shared/DataServices.Client/DataServiceClient.cs, tests/UnitTests/SharedTests/HttpClientFunctionTests/PdsHttpClientMockTests.cs
- the PDS function was throwing an error whenever we would call the fake PDS services
- now gets a fake "real" record from the database by reading the json of the participant from local
---
=> fix: now returns from mocked http function code

application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/Program.cs, application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/RetrievePDSDemographicConfig.cs
This PR updates the Service Bus connection string handling in the RetrievePDSDemographic function to provide more flexible configuration options. The changes add support for an alternative connection string environment variable (`ServiceBusConnectionString_client_internal`) while maintaining backward compatibility with the existing `ServiceBusConnectionString`.
The terraform setup explicitly sets the service bus connection string to ServiceBusConnectionString_client_internal - so this was not being picked up in Program.cs and preventing function startup
--- …
=> fix: Retrieve PDS Demographic - Correct Service Bus connection string handling in configuration

application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/Program.cs, application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/RetrievePDSDemographicConfig.cs
This PR updates the RetrievePDSDemographic function to use a more specific Service Bus connection string configuration. The change replaces the generic `ServiceBusConnectionString` with `ServiceBusConnectionString_client_internal` to match with terraform, without the use of decorators.
RetrievePDSDemographic is still not starting in dev, this hopes to rectify the issue.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. …
=> fix: Retrieve PDS Demographic service bus connection string - named explicitly to match terraform

application/CohortManager/src/Functions/Shared/Common/Pagination/PaginationService.cs, application/CohortManager/src/Functions/Shared/Data/Database/ValidationExceptionData.cs, application/CohortManager/src/Functions/Shared/Model/ExceptionDetails.cs
added SupersededByNhsNumber to ExceptionDetails and changed pagination from 20 to 10 results per page
---
=> feat: added SupersededByNhsNumber to ExceptionDetails and changed pagination from 20 to 10 results per page

infrastructure/tf-core/app_service_plan.tf, infrastructure/tf-core/environments/development.tfvars, infrastructure/tf-core/function_app.tf, infrastructure/tf-core/variables.tf
This change includes a change to the App Service Plan implementation:
- the SKU defined per instance, not globally
- new set of instances with different SKUs and scaling rules, based on the performance analysis
- limit the Max Pool Size to 100 from 300
Changes from this branch have been successfully implemented in Development environment, following a required manual deletion of all the function apps in Dev:
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=25346&view=results
Roll out to NFT and Integration will happen once we're able to take those environments down for 1-2 hours.
--- …
=> feat: DTOSS-10566 define asp SKU per instance

application/CohortManager/src/Web/app/api/GetValidationExceptions/route.ts, application/CohortManager/src/Web/app/types/exceptionsApi/index.d.ts
Adds `supersededByNhsNumber` to the UI mock data following the changes to the API, to allow for testing. Also clean up some of the data that we don't use in the UI in the mock API response (`FileName`/`ErrorRecord`)
---
=> fix: add supersededByNhsNumber and clean up mock data

application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/IPdsProcessor.cs, application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/PdsProcessor.cs, application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/RetrievePDSDemographic.cs, application/CohortManager/src/Functions/NemsSubscriptionService/ProcessNemsUpdate/ProcessNemsUpdate.cs, tests/UnitTests/DemographicServicesTests/RetrievePDSDemographicTests/RetrievePDSDemographicTests.cs, tests/UnitTests/NemsSubscriptionServiceTests/ProcessNemsUpdateTests/ProcessNemsUpdateTests.cs, tests/UnitTests/PdsProcessorTests/PdsProcessorTests.cs
This change updates the NEMS flow to retain the original blob filename for downstream traceability.
- ProcessNemsUpdate now passes the actual blob filename into BasicParticipantCsvRecord (instead of the constant "NemsMessages").
- RetrievePdsDemographic accepts an optional `sourceFileName` and forwards it when creating a BasicParticipantCsvRecord in the PDS 404/invalidated path; when not provided, the existing default is used.
Enable traceability from the NEMS inbound blob through to participant processing by carrying the original blob filename. This aligns logs and audit records without altering existing behavior when no filename is available.
- `RetrievePdsDemographic` now accepts an optional query parameter `sourceFileName`. When provided, records created in the 404/invalidated path …
=> feat: Pass through file names downstream in NEMS process flow

infrastructure/tf-core/environments/integration.tfvars
Updated the ServiceNowUpdateUrl and ServiceNowResolutionUrl environment variables for the integration environment.
They contained the wrong profile key
---
=> fix: Update TF env vars for INT ServiceNow URLs

.azuredevops/templates/cd-infrastructure-core-common.yaml
Remove Terraform deployment stage dependency on retagging stage for the Dev pipeline as retagging is not a required step.
---
=> feat: DTOSS-9902 Remove TF deploy dependency on retagging stage

application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/MockedPDSData/patient-not-found.json, application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/RetrievePDSDemographic.cs, application/CohortManager/src/Functions/Shared/Common/PdsHttpClientMock.cs, application/CohortManager/src/Functions/Shared/Common/Utilities/HTTPStubUtilities.cs
- Adding participant not found response to PDS stub.
- Bug fix in Retrieve PDS Demographic where it tried to deserialise json to the wrong type for invalid records.
When a participant couldn't be found in the mocked (or real) PDS endpoint. 
The function would return a 500 error rather than the correct 404
---
=> fix: PDS not found bug fix

application/CohortManager/compose.core.yaml, application/CohortManager/src/Functions/DemographicServices/ManageNemsSubscription/Program.cs
Setting IsStubbed to true on the managenemssubscription function in local docker setup - this means no certificates are needed to get it up and running.
Local docker based unit tests are failing when the certificate isn't present.
---
=> fix: Set IsStubbed to true by default in local docker compose for NEMS Sub Mgmt

infrastructure/tf-core/environments/nft.tfvars
add APP_ENV to the NFT environment terraform to allow for stubbing of NHS CIS2 login in this environment
---
=> fix: add APP_ENV to the nft terraform

.azuredevops/pipelines/post-deployment-tests-dev.yaml, .azuredevops/pipelines/task_azure_sql_scaling_dev.yaml, .azuredevops/pipelines/task_azure_sql_scaling_int.yaml, .azuredevops/pipelines/task_azure_sql_scaling_nft.yaml, .azuredevops/pipelines/task_azure_sql_scaling_preprod.yaml, .github/workflows/cicd-1-pull-request.yaml, .github/workflows/stage-4-deploy.yaml
Enable end-to-end pipeline process for the Development environment, including ONLY the basic smoke test (running the full suite of tests currently takes to long to be practical in a continuous deployment scenario): 
- smoke_e2e
The automated tests have been scheduled to run earlier in the morning as well in order to be fully completed before the start of the working day.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. …
=> feat: DTOSS-9902 Enable End to End PL in Dev

tests/playwright-tests/src/tests/e2e/epic4c-add-participant-tests/epic4c-10011-10012-testsuite.spec.ts
=> test: fix-4c-regression-failure

application/CohortManager/src/Functions/DemographicServices/ManageCaasSubscription/ManageCaasSubscription.cs, tests/UnitTests/DemographicServicesTests/ManageCaasSubscriptionTests/ManageCaasSubscriptionTests.cs
added idempotent check to ManageCaasSubscription Subscribe endpoint
---
=> fix: added idempotent check to ManageCaasSubscription Subscribe endpoint

infrastructure/tf-core/environments/development.tfvars
The current version of our CAE module does not support more than one CAE resource to be deployed.
There is a conflict due to `ManagedEnvironmentInfrastructureResourceGroupConflict` issue, as setting the value of `infrastructure_resource_group_name` with `"${var.resource_group_name}-cae-infra"`:
This results in the same value for `infrastructure_resource_group_name` across all CAE instances in the environment.
In the long run the module needs to be fixed, but in order to be able to deploy the Wiremock, it's going to be deployed into an existing CAE - `cae-dev-uks-cohman-db-management `.
The fix for the CAE module will contain a breaking change that will require a change across other projects, and will be planned out right after the Wiremock is up and running.
---
To ensure the utmost …
=> fix: deploy wiremock container app into existing CAE

application/CohortManager/src/Functions/ParticipantManagementServices/ManageServiceNowParticipant/ManageServiceNowParticipantFunction.cs, tests/UnitTests/ParticipantManagementServicesTests/ManageServiceNowParticipantTests/ManageServiceNowParticipantFunctionTests.cs
Removed NHS Number from log statement
Shouldn't be logging NHS Numbers
---
=> fix: Removed NHS Number from log statement

application/CohortManager/src/Functions/CohortDistributionServices/DistributeParticipant/DistributeParticipantActivities.cs, application/CohortManager/src/Functions/CohortDistributionServices/DistributeParticipant/ValidateParticipant.cs
[DTOSS-11011](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-11011)
previously the insert time was set to when the first record was inserted for a participant but it needs to be set on a per record basis
---
=> fix: always set record insert time to now

application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/IPdsProcessor.cs, application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/PdsProcessor.cs, application/CohortManager/src/Functions/DemographicServices/RetrievePDSDemographic/RetrievePDSDemographic.cs, tests/UnitTests/DemographicServicesTests/RetrievePDSDemographicTests/RetrievePDSDemographicTests.cs, tests/UnitTests/PdsProcessorTests/PdsProcessorTests.cs
- When NotFound response contains an INVALIDATED_RESOURCE code, a message to remove the participant is only sent if the request is part of a NEMS update.
- Removed call to ProcessPdsNotFoundResponse for participants with ConfidentialityCode == "R"
[DTOSS-10995](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10995)
---
=> fix: Fixes for handling PDS INVALIDATED_RESOURCE code and S flagged patients

application/CohortManager/src/Functions/Shared/Common/Mesh/MeshSendCaasSubscribe.cs, tests/integration-tests/MeshCaaSSubscribeIntegrationTests/ParquetAsserts.cs, tests/integration-tests/MeshCaaSSubscribeIntegrationTests/SendCaasSubscribeTests.cs
CaaS team requested that we send the NHS number in the CaaS Subscribe file to string not long
---
=> feat: change parquet schema for caas subscribe

application/CohortManager/src/Functions/DemographicServices/ManageCaasSubscription/ManageCaasSubscription.cs, application/CohortManager/src/Functions/Shared/Common/Mesh/IMeshSendCaasSubscribe.cs, application/CohortManager/src/Functions/Shared/Common/Mesh/MeshSendCaasSubscribe.cs, application/CohortManager/src/Functions/Shared/Common/Mesh/MeshSendCaasSubscribeStub.cs
Adds another endpoint to create a subscription request to caas with multiple NHS NUmbers
easier cutover for creating mutliple subscriptions
---
=> feat: caas multiple subscribe requests

application/CohortManager/src/Web/app/lib/auth.ts, infrastructure/tf-core/environments/preprod.tfvars, infrastructure/tf-core/environments/production.tfvars
Add Service Now, PDS and CIS config to Prod environment variables so that 3rd party integrations can be completed.
---
=> feat: DTOSS-10962 Add Service Now, PDS and CIS config to Prod environment variables

infrastructure/tf-core/environments/preprod.tfvars, infrastructure/tf-core/environments/production.tfvars
Set SQL Server baseline SKU for Prod and Pre-Prod to S12 to avoid performance issues after rebuilds.
---
=> fix: Set SQL Server baseline SKU for Prod and Pre-Prod

application/CohortManager/src/Web/app/components/participantInformationPanel.tsx, application/CohortManager/src/Web/app/lib/ruleMapping.ts
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-11097
---
=> fix: use the correct portal form title for rule 66

tests/playwright-tests/src/tests/e2e/testFiles/@DTOSS-3883-01/ADDMANUAL1_1B8F53_-_CAAS_BREAST_SCREENING_COHORT.json
Updated test input data
Tests were failing due to ServiceNow test cases with the same number
---
=> test: Fixed e2e test by using unique ServiceNow numbers in test data
